### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by kodlar** [atom/vim-mode#1029]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.1
### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Users/ogan/.atom/packages/vim-mode/lib/vim-state.coffee:276

RangeError: Invalid string length
    at Array.join (native)
    at Put.module.exports.Put.execute (/Users/ogan/.atom/packages/vim-mode/lib/operators/put-operator.coffee:26:44)
    at Repeat.Prefix.execute (/Users/ogan/.atom/packages/vim-mode/lib/prefixes.coffee:21:21)
    at VimState.module.exports.VimState.processOpStack (/Users/ogan/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/Users/ogan/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/Users/ogan/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at atom-text-editor.commands.(anonymous function) (/Users/ogan/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/ogan/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/ogan/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/ogan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/ogan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/ogan/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/ogan/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:00.4.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:00.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:00.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.3.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.3.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.3.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.3.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:00.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.2.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.2.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.1.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:00.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.14.1
atom-typescript, v8.10.2
autocomplete-json, v5.0.2
autocomplete-modules, v1.5.1
autocomplete-paths, v1.0.2
file-type-icons, v1.3.0
language-babel, v2.26.1
linter, v1.11.4
linter-eslint, v7.2.2
minimap, v4.24.3
minimap-pigments, v0.2.1
node-debugger, v1.7.0
pigments, v0.29.1
project-manager, v2.9.7
react, v0.15.0
tree-view-git-branch, v0.1.2
tree-view-git-modified, v0.6.2
tree-view-git-status, v0.2.3
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
