### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by jyltt** [atom/vim-mode#1043]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.1
### Stack Trace

Failed to load the vim-mode package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-mode/lib/vim-mode.coffee:1:37)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/vim-mode/lib/vim-mode.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:167:19)
    at HTMLButtonElement.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:328:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\Administrator\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```
### Commands

```
 12x -7:11 vim-mode-plus:move-up (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -7:05.8.0 vim-mode-plus:insert-below-with-newline (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -7:04.5.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.insert-mode)
  2x -7:04.2.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -7:02.0 core:save (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -6:59.8.0 vim-mode-plus:move-to-first-character-of-line-down (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -6:59.1.0 vim-mode-plus:move-up (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
  2x -6:58.2.0 vim-mode-plus:delete (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -6:57.5.0 vim-mode-plus:move-up (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -6:56.2.0 core:save (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
  3x -6:54.4.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.is-focused.power-mode.vim-mode-plus.normal-mode)
     -1:06.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "vim-mode": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
language-lua, v0.9.4
linter, v1.11.14
linter-lua, v1.0.2
minimap, v4.24.7
relative-numbers, v0.5.1
simplified-chinese-menu, v3.4.11
vim-mode, v0.65.1
vim-mode-plus, v0.46.0

# Dev
No dev packages
```

**Comment by sagar2009kumar** [comment]
Error: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:392:9)
    at compile (C:\Users\Sagar\.atom\packages\gpp-compiler\index.js:274:31)
    at tree-view-file.treeCompile (C:\Users\Sagar\.atom\packages\gpp-compiler\index.js:251:3)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\atom-environment.js:1181:28)
    at EventEmitter.outerCallback (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

What to do with it ..

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
