### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by labmain** [atom/vim-mode#1051]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.1
### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Users/shun/.atom/packages/vim-mode/lib/vim-state.coffee:276

RangeError: Invalid array length
    at Object._.times (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:1118:17)
    at MoveDown.moveCursor (/Users/shun/.atom/packages/vim-mode/lib/motions/general-motions.coffee:212:7)
    at MoveDown.Motion.execute (/Users/shun/.atom/packages/vim-mode/lib/motions/general-motions.coffee:37:8)
    at Repeat.Prefix.execute (/Users/shun/.atom/packages/vim-mode/lib/prefixes.coffee:21:21)
    at VimState.module.exports.VimState.processOpStack (/Users/shun/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/Users/shun/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/Users/shun/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at atom-text-editor.commands.(anonymous function) (/Users/shun/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:30.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:30.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:29.3.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 11x -0:27.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:24.3.0 vim-mode:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:16.8.0 vim-mode:move-to-last-nonblank-character-of-line-and-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:13.6.0 vim-mode:repeat-search (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:11.7.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:09.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -0:08.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:05.5.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:02.3.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.8.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "project-switcher"
    ],
    "projectHome": "/Users/shun/Data"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2 (active)
autocomplete-python, v1.8.6 (active)
file-icons, v1.7.18 (active)
git-plus, v5.16.2 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.37 (active)
language-swift, v0.4.0 (active)
linter, v1.11.16 (active)
linter-clang, v3.4.4 (active)
linter-python, v3.0.5 (active)
linter-swiftc, v2.0.0 (active)
markdown-scroll-sync, v2.1.2 (active)
minimap, v4.24.7 (active)
pretty-json, v1.6.0 (active)
project-manager, v2.9.7 (active)
python-tools, v0.6.8 (active)
script, v3.9.0 (inactive)
selection-highlight, v0.1.5 (active)
seti-ui, v1.3.2 (inactive)
simplified-chinese-menu, v3.4.11 (active)
sync-settings, v0.7.2 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by zombiezen** [comment]
I'm getting this by trying to use the '|' motion.

**Comment by reouno** [comment]
I got the same error by using '|'.
sierra 10.12.4
Atom 1.16.0
vim-mode 0.66.0

**Comment by rsese** [comment]
@reouno - as mentioned in the project README:

https://github.com/atom/vim-mode/blob/master/README.md#current-status---deprecated-in-favor-of-vim-mode-plus

The vim-mode package has been deprecated in favor of vim-mode-plus:

https://github.com/t9md/atom-vim-mode-plus

I'd recommend uninstalling vim-mode and installing vim-mode-plus.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
