### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by mahmoudhossam** [atom/vim-mode#1063]
[Enter steps to reproduce below:]

1. Highlight some text
2. Press "c"

**Atom Version**: 1.10.2
**Electron Version**: 1.4.0
**System**: linux 4.7.4-1-ARCH
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.1

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /home/mahmoud/.atom/packages/vim-mode/lib/vim-state.coffee:276

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at setObjectMembers (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:98:22)
    at loadRemoteProperties (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:164:5)
    at Object.getOwnPropertyDescriptor (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:179:7)
    at Object.descriptor.get [as writeText] (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:118:32)
    at Clipboard.module.exports.Clipboard.write (/usr/lib/atom/src/clipboard.js:25:23)
    at VimState.module.exports.VimState.setRegister (/home/mahmoud/.atom/packages/vim-mode/lib/vim-state.coffee:333:22)
    at Change.Operator.setTextRegister (/home/mahmoud/.atom/packages/vim-mode/lib/operators/general-operators.coffee:54:15)
    at Change.execute (/home/mahmoud/.atom/packages/vim-mode/lib/operators/input.coffee:121:8)
    at VimState.module.exports.VimState.processOpStack (/home/mahmoud/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/home/mahmoud/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/home/mahmoud/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at atom-text-editor.commands.(anonymous function) (/home/mahmoud/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:260:29)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:31.6.0 core:move-down (div.terminal)
     -2:08.3.0 term3:open-split-down (div.terminal)
 17x -1:51.5.0 core:backspace (div.terminal)
  3x -1:48.6.0 core:cancel (div.terminal)
  2x -1:42.7.0 core:confirm (div.terminal)
     -1:30.3.0 term3:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -1:28.7.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:37.6.0 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:35.9.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.4.0 vim-mode:change (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2 (active)
django-templates, v0.5.0 (active)
editorconfig, v1.4.1 (active)
ex-mode, v0.13.0 (inactive)
git-plus, v5.17.1 (inactive)
linter, v1.11.16 (active)
linter-flake8, v1.13.4 (active)
term3, v0.22.1 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
> Electron Version: 1.4.0

This is an unsupported Electron version.  Please uninstall Atom and redownload it from https://atom.io.

https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md

**Comment by mahmoudhossam** [comment]
This is the version that ships on Arch Linux and the latest on http://electron.atom.io/releases/

I think the latest version should be supported.

**Comment by 50Wliu** [comment]
> This is the version that ships on Arch Linux and the latest on http://electron.atom.io/releases/

That does not matter: Atom does not currently support that Electron version.  Atom and Electron are two very different projects.  Please read the linked document for more information.

**Comment by mahmoudhossam** [comment]
Arch Linux ships Electron 1.4.0 https://www.archlinux.org/packages/community/x86_64/electron/ and you can also see on this page that arch ships a version of atom that depends on it.

**Comment by 50Wliu** [comment]
My point still stands - neither that Electron package nor the Atom package are maintained by GitHub.
