### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by v0d1ch** [atom/vim-mode#1087]
[Enter steps to reproduce:]

1. close file with cmd-w

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package 0.66.0

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /Users/v0d1ch/.atom/packages/vim-mode/lib/vim-state.coffee:276

TypeError: Cannot read property 'classList' of null
    at VimState.module.exports.VimState.changeModeClass (/packages/vim-mode/lib/vim-state.coffee:551:23)
    at VimState.module.exports.VimState.activateNormalMode (/packages/vim-mode/lib/vim-state.coffee:398:6)
    at Replace.module.exports.Replace.execute (/packages/vim-mode/lib/operators/replace-operator.coffee:19:19)
    at VimState.module.exports.VimState.processOpStack (/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/packages/vim-mode/lib/vim-state.coffee:237:8)
    at ViewModel.cancel (/packages/vim-mode/lib/view-models/view-model.coffee:15:17)
    at /packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:52:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
```

### Commands

```
     -0:52.9.0 termrk:activate-next-terminal (input.input-keylistener)
     -0:52.2.0 pane:show-next-recently-used-item (input.input-keylistener)
     -0:52.2.0 termrk:activate-next-terminal (input.input-keylistener)
     -0:51.3.0 pane:move-active-item-to-top-of-stack (input.input-keylistener)
     -0:48.5.0 termrk:activate-next-terminal (input.input-keylistener)
     -0:47.6.0 pane:move-active-item-to-top-of-stack (input.input-keylistener)
  2x -0:37.1.0 termrk:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.ide-haskell.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:34.5.0 termrk:activate-next-terminal (input.input-keylistener)
     -0:33.3.0 pane:show-next-recently-used-item (input.input-keylistener)
     -0:32.1.0 pane:move-active-item-to-top-of-stack (input.input-keylistener)
     -0:31.4.0 termrk:activate-next-terminal (input.input-keylistener)
     -0:31.2.0 pane:move-active-item-to-top-of-stack (input.input-keylistener)
     -0:30.5.0 termrk:toggle (input.input-keylistener)
     -0:16.9.0 vim-mode:replace (input.hidden-input)
     -0:14.8.0 core:close (input.hidden-input)
  4x -0:11.1.0 blur (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
angularjs-snippets 0.10.18 
atom-beautify 0.29.17 
autocomplete-haskell 0.7.2 
editorconfig 2.2.0 
ex-mode 0.13.1 
git-blame 0.4.11 
git-checkout 0.3.2 
git-plus 7.2.2 
git-time-machine 1.5.4 
haskell-ghc-mod 1.19.6 
ide-haskell 1.9.3 
ide-haskell-cabal 1.7.5 
ide-haskell-repl 0.5.2 
jslint 1.5.1 
language-haskell 1.12.1 
merge-conflicts 1.4.4 
necro-syntax 1.0.0 
nord-atom-ui 0.10.1 
pipe 0.4.0 
Termrk 0.3.1 
vim-mode 0.66.0 
vim-mode-plus 0.82.0 
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
