### ISSUE TITLE
The error was thrown from the vim-mode package. This issue has already been reported

### ISSUE THREAD

**Issue by rubielhum** [atom/vim-mode#1095]
Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Error (native)
    at vim-normal-mode-input.VimNormalModeInputElement.removePanel (file:///C:/Users/My/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:60:12)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (file:///C:/Users/My/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:46:6)
    at file:///C:/Users/My/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:33:10
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:701:26)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:685:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:574:25)
    at Selection.module.exports.Selection.insertText (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\selection.js:480:49)
    at C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:1127:35
    at C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:1166:34
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:849:24)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:1599:32)
    at C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:1160:30
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:2577:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:2539:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:1158:25)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor.js:1124:25)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor-component.js:480:32)
    at HTMLDivElement.<anonymous> (C:\Users\My\AppData\Local\atom\app-1.18.0\resources\app\src\text-editor-component.js:3:65)

**Comment by rsese** [comment]
Thanks for the report!  Closing since this package has been deprecated in favor of [vim-mode-plus](https://atom.io/packages/vim-mode-plus):

https://github.com/atom/vim-mode#current-status---deprecated-in-favor-of-vim-mode-plus

You may want to give that package a try.
