### ISSUE TITLE
hi atom vim-mode dev

### ISSUE THREAD

**Issue by JinSung-Hwang** [atom/vim-mode#1096]
hi im korea dev

im using vim-mode in atom

i have issue

i hiting 'f' key in vim-mode

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Error (native)
    at vim-normal-mode-input.VimNormalModeInputElement.removePanel (/Users/jinsunghwang/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:60:12)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (/Users/jinsunghwang/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:46:6)
    at /Users/jinsunghwang/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:33:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:701:26)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:685:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:574:25)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:480:49)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1127:35
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1166:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1599:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1160:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2577:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2539:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1158:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1124:25)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:480:32)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:65)

how to fix this error ?

**Comment by kblee152** [comment]
See below contents.
---
[Readme](https://github.com/atom/vim-mode/blob/master/README.md)
Current Status - DEPRECATED in favor of vim-mode-plus
We're not maintaining this package anymore, because vim-mode-plus has more features and is very well maintained.

**Comment by winstliu** [comment]
Yes, please switch to vim-mode-plus which does not have this error.
