### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

### ISSUE THREAD

**Issue by MeynL** [atom/vim-mode#1099]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package 0.66.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At C:\Users\Administrator\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:854

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Error (native)
    at /packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:61:12)
    at /packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:46:6)
    at /packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:33:10
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:701:26)
    at TextBuffer.module.exports.TextBuffer.applyChange (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:685:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:574:25)
    at Selection.module.exports.Selection.insertText (~/AppData/Local/atom/app-1.18.0/resources/app/src/selection.js:480:49)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1127:35
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1166:34
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1599:32)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1160:30
    at TextEditor.module.exports.TextEditor.mergeSelections (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:2577:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:2539:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1158:25)
    at TextEditor.module.exports.TextEditor.insertText (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:1124:25)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor-component.js:480:32)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor-component.js:3:65)
```

### Commands

`f`
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.23 
emmet 2.4.3 
ex-mode 0.17.0 
jquery-snippets 11.0.0 
nord-atom-syntax 0.9.1 
seti-ui 1.7.0 
vim-mode 0.66.0 
```

**Comment by rizowski** [comment]
Duplicate issue?
https://github.com/atom/vim-mode/issues/642

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
