### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by cholcombe973** [atom/vim-mode#1101]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package 0.66.0

### Stack Trace

Uncaught Error: Connection is closed.

```
At /home/chris/.atom/packages/vim-mode/lib/vim-state.coffee:276

Error: Connection is closed.
    at /packages/ide-rust/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-rust/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-rust/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-rust/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-rust/node_modules/atom-languageclient/build/lib/languageclient.js:137:10)
    at TextEditorSyncAdapter.sendIncrementalChanges (/packages/ide-rust/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:204:24)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1674:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1811:30)
    at Delete.execute (/packages/vim-mode/lib/operators/general-operators.coffee:89:15)
    at VimState.module.exports.VimState.processOpStack (/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/packages/vim-mode/lib/vim-state.coffee:237:8)
    at /packages/vim-mode/lib/vim-state.coffee:209:45)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  2x -0:33.8.0 window:toggle-menu-bar (input.hidden-input)
     -0:19.8.0 tree-view:toggle (input.hidden-input)
  4x -0:14 vim-mode:delete (input.hidden-input)
     -0:13.1.0 vim-mode:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.7.0 
atom-jinja2 0.6.0 
busy-signal 1.4.3 
docblockr 0.13.4 
ex-mode 0.18.0 
goto 1.8.3 
ide-rust 0.8.0 
intentions 1.1.5 
language-capnproto 0.3.0 
language-protobuf 0.7.1 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.4 
linter-ui-default 1.6.10 
python-tools 0.6.9 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
tool-bar 1.1.0 
vim-mode 0.66.0 
web-browser 1.5.0 
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
