### ISSUE TITLE
Duplicate VimStates being created after updating vim-mode

### ISSUE THREAD

**Issue by QuillyT** [atom/vim-mode#480]
see https://github.com/atom/vim-mode/issues/478 for more information.

The difference between issue #478 and this is
- #478 was addressing duplication of VimState when moving a file between split panes
- After updating vim-mode, it seems like a "global" VimState is being duplicated.

In this case, all files experience the duplication issue and closing and re-opening files does not remove the problem.

(I'm not sure if this is actually a problem and that we should be restarting Atom when updating packages anyway... in which case we can just close this issue.)

**Comment by maxbrunsfeld** [comment]
Is this still happening? I don't know why it happened originally, but I haven't seen it happen for the past few updates.

**Comment by QuillyT** [comment]
hm, I haven't been looking for along with the updates that I've been doing... but that also means I haven't noticed it either. Can't verify that I haven't just missed it as I've been doing a decent amount of restarting lately.

**Comment by maxbrunsfeld** [comment]
Ok, let's keep it open for now. I think it might be fixed though; can you try and see if anything strange happens on your next update?

**Comment by QuillyT** [comment]
yep, i'll let you know

On Fri, Feb 20, 2015 at 12:17 PM, Max Brunsfeld <notifications@github.com>
wrote:

> Ok, let's keep it open for now. I think it might be fixed though; can you
> try and see if anything strange happens on your next update?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/vim-mode/issues/480#issuecomment-75278778>.
>



-- 
Quentin Tai


CTO/Co-founder Lynxsy
c: 240.994.6563
e: quentin@lynxsy.com
Sign Up! Lynxsy <http://lynxsy.com/>
Follow Us: Facebook <https://www.facebook.com/Lynxsy> | Twitter
<https://twitter.com/LynxsySays>

**Comment by maxbrunsfeld** [comment]
Ah, I see it. It's because sometimes `vim-mode` fails to deactivate with an error like this:

```
Error deactivating package 'vim-mode' TypeError: Cannot read property 'setInputEnabled' of null
  at VimState.module.exports.VimState.destroy (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-state.coffee:46:29)
  at Disposable.disposalAction (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-mode.coffee:31:20)
  at Disposable.module.exports.Disposable.dispose (/Users/maxbrunsfeld/.atom/packages/vim-mode/node_modules/event-kit/lib/disposable.js:21:65)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Users/maxbrunsfeld/.atom/packages/vim-mode/node_modules/event-kit/lib/composite-disposable.js:28:22)
  at Object.module.exports.deactivate (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-mode.coffee:34:18)
  at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app/src/package.js:603:21)
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:501:12)
  at PackageManager.module.exports.PackageManager.update (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:215:23)
  at PackageUpdateView.module.exports.PackageUpdateView.upgrade (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-update-view.js:175:34)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-update-view.js:78:24)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)
/Applications/Atom.app/Contents/Resources/app/src/package.js:608 module.exports.Package.deactivate
```

That error prevents the command listeners from being unregistered.
