### ISSUE TITLE
Cannot run package specs

### ISSUE THREAD

**Issue by peterjeliot** [atom/vim-mode#485]
When I download this repo, open it in atom, and run the specs (view > developer > run atom specs), I get this error in the JS console. This occurs even with no packages installed and a fresh copy of Atom.

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/peterjeliot/Code/vim-mode/lib/vim-state.coffee:1:5)
  at Object.<anonymous> (/Users/peterjeliot/Code/vim-mode/lib/vim-state.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:65:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/peterjeliot/Code/vim-mode/spec/spec-helper.coffee:1:12)
  at Object.<anonymous> (/Users/peterjeliot/Code/vim-mode/spec/spec-helper.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:65:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/peterjeliot/Code/vim-mode/spec/motions-spec.coffee:1:11)
  at Object.<anonymous> (/Users/peterjeliot/Code/vim-mode/spec/motions-spec.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:65:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at requireSpecs (/Applications/Atom.app/Contents/Resources/app/spec/spec-suite.coffee:8:5)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/spec-suite.coffee:52:3)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/spec-suite.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:65:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at module.exports.runSpecSuite (/Applications/Atom.app/Contents/Resources/app/spec/jasmine-helper.coffee:36:3)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/spec-bootstrap.coffee:24:3)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/spec-bootstrap.coffee:2:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:65:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:59:25)
index.js:73 window.onload

**Comment by peterjeliot** [comment]
Ah, this was a failure of understanding of package development things. You need to run "apm install" in the vim-mode directory first.
