### ISSUE TITLE
onDidActivateInitialPackages is undefined

### ISSUE THREAD

**Issue by johngeorgewright** [atom/vim-mode#488]
Just updated "vim-mode" and it's no longer working. This is the error I'm receiving:

```
Failed to activate package named 'vim-mode' TypeError: undefined is not a function
  at StatusBarManager.module.exports.StatusBarManager.initialize (/home/john/.atom/packages/vim-mode/lib/status-bar-manager.coffee:19:38)
  at Object.module.exports.activate (/home/john/.atom/packages/vim-mode/lib/vim-mode.coffee:21:39)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:227:27)
  at /usr/share/atom/resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:404:21)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:393:14)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:379:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:601:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:59:25)
 ```

It seems to be coming from [this change](https://github.com/atom/vim-mode/blob/41ca3b776b99ed042ef09d0f77fc63c7886b1ad7/lib/status-bar-manager.coffee#L18). Apparently `onDidActivateInitialPackages` is undefined.

I'm using Atom 0.161.0 on Ubuntu.

**Comment by kevinsawicki** [comment]
Can you try upgrading your Atom version? I believe it will be fixed if you upgrade to Atom 0.174 or later.

**Comment by johngeorgewright** [comment]
Hmm. I don't seem to have any updates available. I may to build from source.

**Comment by johngeorgewright** [comment]
Oh wait... sorry, I thought I had installed atom through a software source. Looks like I have to upgrade manually. Sucky.

**Comment by johngeorgewright** [comment]
Yep. All is now well. Thanks.
