### ISSUE TITLE
vim-mode fails to start

### ISSUE THREAD

**Issue by LandonSchropp** [atom/vim-mode#494]
When I try to start vim-mode, nothing happens. I popped open the console and found the following error:

```
Failed to activate package named 'vim-mode' TypeError: undefined is not a function
  at StatusBarManager.module.exports.StatusBarManager.initialize (/Users/landon/.dotfiles/atom/packages/vim-mode/lib/status-bar-manager.coffee:18:38)
  at Object.module.exports.activate (/Users/landon/.dotfiles/atom/packages/vim-mode/lib/vim-mode.coffee:21:39)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:227:27)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:404:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:295:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:576:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:71:11)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:551:29)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:189:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:336:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:123:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-package-view.js:185:27)
  at HTMLButtonElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:110:34)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
```

**Comment by holzdev** [comment]
Same here.

**Comment by maxbrunsfeld** [comment]
What version of Atom are you using? Can you upgrade to the latest version and report whether or not this still occurs?

**Comment by holzdev** [comment]
Sorry for the missing details. 
Atom 0.155.0 running on 64bit Windows 8. 
The error occurred after updating the plug-in.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Max Brunsfeld <notifications@github.com> </div><div>Datum:26.01.2015  21:52  (GMT+01:00) </div><div>An: atom/vim-mode <vim-mode@noreply.github.com> </div><div>Cc: holzdev <paul.holz@posteo.de> </div><div>Betreff: Re: [vim-mode] vim-mode fails to start (#494) </div><div>
</div>What version of Atom are you using? Can you upgrade to the latest version and report whether or not this still occurs?

**Comment by maxbrunsfeld** [comment]
Ok, thanks. Upgrading Atom to the latest version will fix this error.

**Comment by holzdev** [comment]
Sorry for the false positive.

**Comment by LandonSchropp** [comment]
Yep, that seemed to solve it for me too. Thanks!
