### ISSUE TITLE
Uncaught Error: Cannot create a checkpoint inside of a transaction

### ISSUE THREAD

**Issue by yriveiro** [atom/vim-mode#505]
[Enter steps to reproduce below:]

Copy and paste code from an example in the web

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.30.0

### Stack Trace

Uncaught Error: Cannot create a checkpoint inside of a transaction

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:174

Error: Cannot create a checkpoint inside of a transaction
  at History.module.exports.History.createCheckpoint (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:174:15)
  at TextBuffer.module.exports.TextBuffer.createCheckpoint (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:710:27)
  at TextEditor.module.exports.TextEditor.createCheckpoint (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor.js:1197:26)
  at VimState.module.exports.VimState.setInsertionCheckpoint (/Users/yagoriveiro/.atom/packages/vim-mode/lib/vim-state.coffee:364:36)
  at VimState.module.exports.VimState.activateInsertMode (/Users/yagoriveiro/.atom/packages/vim-mode/lib/vim-state.coffee:358:6)
  at Insert.execute (/Users/yagoriveiro/.atom/packages/vim-mode/lib/operators/input.coffee:27:17)
  at VimState.module.exports.VimState.processOpStack (/Users/yagoriveiro/.atom/packages/vim-mode/lib/vim-state.coffee:246:23)
  at VimState.module.exports.VimState.pushOperations (/Users/yagoriveiro/.atom/packages/vim-mode/lib/vim-state.coffee:207:8)
  at atom-text-editor.commands.(anonymous function) (/Users/yagoriveiro/.atom/packages/vim-mode/lib/vim-state.coffee:179:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -1:31.5 core:save (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
  2x -1:29.4 core:move-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
  6x -0:49.9 core:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:49.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
  8x -0:48.7 vim-mode:delete (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:46.5 core:save (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:13.5 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:13.2 core:paste (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:11.5 core:save (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
  3x -0:03.4 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:02.6 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:02.2 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:01.8 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:01.2 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:01.2 core:paste (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
     -0:01.1 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.0.12
color-picker, v1.4.4
compare-files, v0.3.1
file-icons, v1.4.8
gocode, v0.2.1
linter, v0.11.1
minimap, v4.1.0
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v4.0.0
minimap-selection, v3.1.1
project-manager, v1.15.5
script, v2.16.0
travis-ci-status, v0.11.2
vim-mode, v0.30.0
zentabs, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by maxbrunsfeld** [comment]
The root cause is some other package that is leaving an editor transaction open using [the deprecated open-ended transaction APIs](https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee#L836). The  `gocode` package's deprecated [uses these](https://github.com/typester/atom-gocode/blob/master/lib/autocomplete-view.coffee#L89). Can you disable that package and try again?

**Comment by yriveiro** [comment]
I closed and opened again the file and the error didn't reproduce.

I will open a issue in `gocode` package alerting of the use of deprecated stuff.

Thanks.
