### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by aadonskoy** [atom/vim-mode#515]
[Enter steps to reproduce below:]
1. Press '/'
2. Fill for example: 'def show', then press 'Enter'
3. Again press '/'
4. Press up-key to previous search string.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.31.0
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:40

TypeError: Cannot read property 'split' of undefined
  at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:40:19)
  at TextBuffer.module.exports.TextBuffer.buildPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:523:24)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:501:20)
  at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:431:19)
  at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:741:26)
  at TextEditorView.module.exports.TextEditorView.setText (/Applications/Atom.app/Contents/Resources/app/src/text-editor-view.js:376:25)
  at SearchViewModel.module.exports.SearchViewModel.restoreHistory (/Users/alexey/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:13:18)
  at SearchViewModel.module.exports.SearchViewModel.increaseHistorySearch (/Users/alexey/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:21:8)
  at atom-text-editor.<anonymous> (/Users/alexey/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:1:1)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```
### Commands

```
  2x -0:49.8 vim-mode:move-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
  2x -0:46.5 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
 43x -0:41.4 vim-mode:move-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
 57x -0:39.2 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
 15x -0:36.9 vim-mode:move-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
  2x -0:35.7 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
 38x -0:35.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
 91x -0:18.7 vim-mode:move-up (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
     -0:10.8 vim-mode:search (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
     -0:04.4 core:confirm (atom-text-editor.editor.mini)
     -0:03.2 vim-mode:search (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
     -0:02.9 core:confirm (atom-text-editor.editor.mini)
     -0:02.4 vim-mode:search (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
     -0:02.1 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 vim-mode:search (atom-text-editor.editor.vim-mode.autocomplete-active.command-mode)
     -0:00.7 core:move-up (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.5.5
autocomplete-plus, v2.1.3
emmet, v2.3.3
highlight-column, v0.4.0
highlight-line, v0.9.3
indent-guide-improved, v1.1.1
language-haml, v0.15.0
linter-rubocop, v0.2.1
set-syntax, v0.2.1
trailing-spaces, v0.2.4
vim-mode, v0.31.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
