### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trimLeft' of undefined

### ISSUE THREAD

**Issue by bradleyflood** [atom/vim-mode#522]
Step taken in this instance:
Hit `o` to insert new line, then hit `delete (backspace)` to delete current line and move up one line, below error was then thrown.

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.31.0
### Stack Trace

Uncaught TypeError: Cannot read property 'trimLeft' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'trimLeft' of undefined
  at InsertBelowWithNewline.execute (/Users/tom/.atom/packages/vim-mode/lib/operators/input.coffee:61:30)
  at /Users/tom/.atom/packages/vim-mode/lib/operators/general-operators.coffee:199:22
  at Object._.times (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/underscore/underscore.js:1119:53)
  at /Users/tom/.atom/packages/vim-mode/lib/operators/general-operators.coffee:198:5
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at Repeat.execute (/Users/tom/.atom/packages/vim-mode/lib/operators/general-operators.coffee:197:3)
  at VimState.module.exports.VimState.processOpStack (/Users/tom/.atom/packages/vim-mode/lib/vim-state.coffee:236:5)
  at VimState.module.exports.VimState.pushOperations (/Users/tom/.atom/packages/vim-mode/lib/vim-state.coffee:191:7)
  at atom-text-editor.commands.(anonymous function) (/Users/tom/.atom/packages/vim-mode/lib/vim-state.coffee:177:5)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```
### Commands

```
     -0:33.4 core:confirm (atom-text-editor.editor.mini)
     -0:22.7 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:20.5 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:19.8 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:19.8 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:19.8 editor:newline (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:18.2 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:17.7 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:16.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:16.4 core:cancel (atom-text-editor.editor.mini)
     -0:10.3 tree-view:toggle (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:05.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.3 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.6 core:backspace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.4 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.9 vim-mode:repeat (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".aspx.cs*"
    ],
    "disabledPackages": [
      "file-types",
      "language-objective-c",
      "language-c",
      "language-clojure",
      "language-go",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "minimap-git-diff",
      "git-diff",
      "git-log",
      "minimap-find-and-replace",
      "archive-view",
      "wrap-guide",
      "autoflow",
      "autosave"
    ]
  },
  "vim-mode": {
    "startInInsertMode": true
  }
}
```
### Installed Packages

``` coffee
# User
docblockr, v0.5.8
emmet, v2.3.3
highlight-line, v0.9.3
language-aspx, v0.2.0
minimap, v4.1.4
vim-mode, v0.31.0

# Dev
No dev packages
```

**Comment by bradleyflood** [comment]
Looks to be related to #497 
Removing package, restarting Atom and reinstalling fixes the backspace issue.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
