### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setInputEnabled' of null

### ISSUE THREAD

**Issue by trevrus** [atom/vim-mode#529]
[Enter steps to reproduce below:]
1. Open more than one pane. Drag a file from one pane to the other pane.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.21.0
### Stack Trace

Uncaught TypeError: Cannot read property 'setInputEnabled' of null

```
At /Users/Trevor/.atom/packages/vim-mode/lib/vim-state.coffee:362

TypeError: Cannot read property 'setInputEnabled' of null
  at VimState.module.exports.VimState.deactivateInsertMode (/Users/Trevor/.atom/packages/vim-mode/lib/vim-state.coffee:362:29)
  at VimState.module.exports.VimState.activateCommandMode (/Users/Trevor/.atom/packages/vim-mode/lib/vim-state.coffee:332:6)
  at new VimState (/Users/Trevor/.atom/packages/vim-mode/lib/vim-state.coffee:39:8)
  at /Users/Trevor/.atom/packages/vim-mode/lib/vim-mode.coffee:26:22
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:279:16
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:336:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:379:27)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:348:20)
  at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app/src/pane.js:432:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:561:18)
  at TabBarView.module.exports.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:484:23)
  at space-pen-ul.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```
### Commands

```
     -0:47.9 core:move-right (atom-text-editor.editor.mini)
     -0:46.4 core:move-left (atom-text-editor.editor.mini)
     -0:43.1 core:backspace (atom-text-editor.editor.mini)
     -0:06.2 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus",
      "autocomplete-snippets",
      "linter-tidy"
    ],
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.17.2
color-picker, v1.2.6
linter, v0.9.0
linter-jshint, v0.1.0
seti-ui, v0.5.1
terminal-status, v1.3.5
turbo-javascript, v0.0.5
vim-mode, v0.21.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
