### ISSUE TITLE
Failed to load the vim-mode package

### ISSUE THREAD

**Issue by jasper-fu** [atom/vim-mode#584]
[Enter steps to reproduce below:]

1. OPEN atom

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.39.0

### Stack Trace

Failed to load the vim-mode package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/jasper/.atom/packages/vim-mode/lib/vim-mode.coffee:4:10)
    at Object.<anonymous> (/Users/jasper/.atom/packages/vim-mode/lib/vim-mode.coffee:64:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "script"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-alignment, v0.11.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
color-picker, v1.4.4
dash, v1.0.3
emmet, v2.3.4
language-haml, v0.15.0
language-rspec, v0.3.0
minimap, v4.6.0
minimap-git-diff, v4.1.2
monokai, v0.12.0
rspec-snippets, v0.4.0
vim-mode, v0.39.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
It looks like you installed `vim-mode` manually, by cloning this repo into `~/.atom/packages`. That works, but you need to run `apm install` from the `vim-mode` directory first.

**Comment by calebmeyer** [comment]
I installed vim-mode using the packages view in the settings, and I am getting this issue. I ran `apm-install` in ~/.atom/packages/vim-mode, but I still get the error mentioned above.
Atom 0.190.0
vim-mode 0.43.0
Mac OS X 10.10.3

**Comment by jasper-fu** [comment]
@calebmeyer I installed vim-mode using the packages too, maxbrunsfeld's solution fixed my issues though.

**Comment by maxbrunsfeld** [comment]
Closing as @jasper-fu's issue is resolved. @calebmeyer when you see this next, can you click the button to report the issue so I can see your details?

**Comment by calebmeyer** [comment]
@maxbrunsfeld Issue is magically fixed this morning. I wonder if rebooting my mac fixed it. I'll raise a new issue if I see it again.

**Comment by airstrike** [comment]
```
Cannot find module 'event-kit'
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\André\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\André\.atom\packages\vim-mode\lib\vim-mode.coffee:1:37)
    at Object.<anonymous> (C:\Users\André\.atom\packages\vim-mode\lib\vim-mode.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\André\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
