### ISSUE TITLE
Cannot read property 'hiddenInputComponent' of null

### ISSUE THREAD

**Issue by octref** [atom/vim-mode#587]
1. Open a file
2. Use `/` to search for something + `Enter`

The problem seems to be here.
https://github.com/atom/atom/blob/master/src/text-editor-element.coffee#L134-L140
I don't quite understand what this check is for:
`if event.relatedTarget is @component.hiddenInputComponent.domNode` 
so I didn't go further.

Enabling Shadow DOM temporarily solves the problem.

\\*\\*Atom Version\\*\\*: 0.188.0-6c38562
\\*\\*System\\*\\*: linux 3.19.2-1-ARCH
\\*\\*Thrown From\\*\\*: [vim-mode](https://github.com/atom/vim-mode) package, v0.40.0

### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /home/pine/atom-build/Atom/resources/app/src/text-editor-element.js:199

TypeError: Cannot read property 'hiddenInputComponent' of null
  at atom-text-editor.TextEditorElement.blurred (/home/pine/atom-build/Atom/resources/app/src/text-editor-element.js:199:51)
  at HTMLInputElement.<anonymous> (/home/pine/atom-build/Atom/resources/app/src/text-editor-element.js:174:26)
  at atom-pane.PaneElement.activated (/home/pine/atom-build/Atom/resources/app/src/pane-element.js:91:19)
  at Emitter.module.exports.Emitter.emit (/home/pine/atom-build/Atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/home/pine/atom-build/Atom/resources/app/src/pane.js:651:27)
  at VimCommandModeInputView.module.exports.VimCommandModeInputView.remove (/home/pine/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-view.coffee:52:36)
  at VimCommandModeInputView.remove (/home/pine/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-view.coffee:1:1)
  at VimCommandModeInputView.module.exports.VimCommandModeInputView.confirm (/home/pine/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-view.coffee:42:6)
  at atom-text-editor.<anonymous> (/home/pine/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-view.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/pine/atom-build/Atom/resources/app/src/command-registry.js:242:29)
  at /home/pine/atom-build/Atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/home/pine/atom-build/Atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/pine/atom-build/Atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/home/pine/atom-build/Atom/resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
 46x -1:41.2 vim-mode:move-down (input.hidden-input)
     -1:25.8 vim-mode:insert-below-with-newline (input.hidden-input)
     -1:25.2 vim-mode:reset-command-mode (input.hidden-input)
     -1:24.9 vim-mode:undo (input.hidden-input)
     -1:24.5 vim-mode:move-up (input.hidden-input)
     -1:23.5 vim-mode:scroll-half-screen-up (input.hidden-input)
  8x -1:22.8 vim-mode:move-up (input.hidden-input)
     -1:21.5 vim-mode:move-to-bottom-of-screen (input.hidden-input)
     -1:21.0 vim-mode:move-to-middle-of-screen (input.hidden-input)
 31x -1:20.0 vim-mode:move-down (input.hidden-input)
 28x -1:17.3 vim-mode:move-up (input.hidden-input)
     -0:47.1 settings-view:open (input.hidden-input)
 12x -0:03.5 vim-mode:move-up (input.hidden-input)
     -0:01.5 vim-mode:search (input.hidden-input)
     -0:00.6 editor:newline (input.hidden-input)
  3x -0:00.6 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "view-tail-large-files"
    ],
    "audioBeep": false
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
language-lua, v0.9.0
vim-mode, v0.40.0

# Dev
No dev packages
```

**Comment by jacekkopecky** [comment]
I also have this problem when using v.40

**Comment by jacekkopecky** [comment]
In my case, the problem has gone away after enabling "use shadow DOM" in the main settings - I can't remember why I disabled it.

**Comment by octref** [comment]
@jacekkopecky 
Atom says this option will eventually go away, so we can't rely on that.

**Comment by jacekkopecky** [comment]
My interpretation seems to differ: the option in Atom is described as 

**Use Shadow DOM**
```
Disable if you experience styling issues with packages or themes. Be sure to open an issue on the relevant package or theme, because this option is going away eventually.
```

I read that as meaning the option to *disable* shadow DOM is going away, and it was *enabling* shadow DOM that fixed the issue for me.

**Comment by octref** [comment]
@jacekkopecky 
You're right. I should have looked at the option more closely. Thanks!
