### ISSUE TITLE
Delete Until operator

### ISSUE THREAD

**Issue by romgrk** [atom/vim-mode#618]
1. Place cursor on line (cursor is on the first /)

     _ = require '**/**usr/share/atom/resources/app/node_modules/underscore-plus'

2. Keydown 'dtu'

EDIT: The probleme here is that the **dtu** command considers that the **u** is next, so there is nothing to delete. Which is false, because it should normally delete at least the **/**.

**Atom Version**: 0.188.0
**System**: linux 3.16-3-amd64
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.43.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /home/romgrk/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at /home/romgrk/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8:43
  at Emitter.module.exports.Emitter.emit (/home/romgrk/.atom/packages/vim-mode/node_modules/event-kit/lib/emitter.js:71:11)
  at VimState.module.exports.VimState.pushOperations (/home/romgrk/.atom/packages/vim-mode/lib/vim-state.coffee:209:18)
  at atom-text-editor.commands.(anonymous function) (/home/romgrk/.atom/packages/vim-mode/lib/vim-state.coffee:192:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:242:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
  2x -0:05.2 window:toggle-full-screen (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.9 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.4 vim-mode:till (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:02.1 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.5 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.2 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:01.1 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.4 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "jellybeans-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.6.1
autocomplete-plus, v2.7.1
color-picker, v1.6.0
file-icons, v1.5.4
jellybeans-syntax, v0.3.0
project-manager, v1.15.5
vim-mode, v0.43.0
vim-surround, v0.5.0

# Dev
No dev packages
```

**Comment by romgrk** [comment]
#623
