### ISSUE TITLE
Null error with jumpy package

### ISSUE THREAD

**Issue by LukeMauldin** [atom/vim-mode#631]
1.Install package jumpy
2. Add key binding:
 `'.atom-text-editor:not(.mini).vim-mode:not(.insert-mode):not(.jumpy-jump-mode)':
    'f': 'jumpy:toggle'`
3. Fit key 'f' when in normal mode.

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.44.0
### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:205

TypeError: Cannot read property 'hiddenInputComponent' of null
    at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:205:51)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:180:26)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:102:19)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:591:27)
    at vim-command-mode-input.VimCommandModeInputElement.removePanel (/Users/lmauldin/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:81:38)
    at vim-command-mode-input.VimCommandModeInputElement.confirm (/Users/lmauldin/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:68:19)
    at /Users/lmauldin/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:53:28
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:550:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:461:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:452:43)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:716:31
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:758:29
    at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:119:18)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:647:27)
```
### Commands

```
     -0:25.4 vim-mode:find (input.hidden-input)
     -0:23.7 editor:consolidate-selections (input.hidden-input)
     -0:23.7 core:cancel (input.hidden-input)
 24x -0:23.7 blur (input.hidden-input)
     -0:04.9 vim-mode:find (input.hidden-input)
  6x -0:04.9 blur (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "grunt-runner",
      "linter-phpcs",
      "gocode",
      "go-oracle",
      "atom-ctags",
      "transient-emacs"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atomatigit, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
command-logger, v0.23.0
editor-stats, v0.17.0
editorconfig, v0.3.3
git-log, v0.3.0
go-plus, v3.3.7
language-laravel-blade, v0.2.0
laravel, v0.4.2
laravel-facades, v1.0.0
linter-jshint, v0.1.2
linter-php, v0.0.12
pain-split, v1.3.1
script, v2.19.0
symbols-tree-view, v0.9.2
tabs-to-spaces, v0.9.2
vim-mode, v0.44.0

# Dev
No dev packages
```

**Comment by LukeMauldin** [comment]
Receive same error even if I just do a normal search using `/texthere`

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
