### ISSUE TITLE
Error on normal mode

### ISSUE THREAD

**Issue by gokmen** [atom/vim-mode#633]
In `normal` ( or `command` for this package) mode when I press `c` `m` it crashes with following stack trace.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.44.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Users/gokmen/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at /Users/gokmen/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8:43
  at Emitter.module.exports.Emitter.emit (/Users/gokmen/.atom/packages/vim-mode/node_modules/event-kit/lib/emitter.js:71:11)
  at VimState.module.exports.VimState.pushOperations (/Users/gokmen/.atom/packages/vim-mode/lib/vim-state.coffee:209:18)
  at atom-text-editor.commands.(anonymous function) (/Users/gokmen/.atom/packages/vim-mode/lib/vim-state.coffee:192:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
  2x -0:21.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:20.3.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:14.6.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:10.7.0 vim-mode:change (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:10.6.0 vim-mode:mark (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:10.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:10 vim-mode:put-after (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:06.9.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:05.8.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:05.3.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.8.0 application:new-file (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:02.7.0 blur (atom-text-editor.editor.vim-mode.command-mode)
     -0:01.2.0 vim-mode:change (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.1.0 vim-mode:mark (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:01.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.8.0 vim-mode:put-after (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-coffee-repl",
      "coffee-trace",
      "compare-files",
      "synced-sidebar",
      "git-control",
      "gocode",
      "go-find-references",
      "atom-cli-diff",
      "custom-title",
      "symbols-tree-view",
      "tree-view-open-files",
      "resize-panes",
      "atom-pair",
      "omni-ruler",
      "rulerz"
    ],
    "followSymlinks": true,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
autocomplete-plus, v2.12.0
coffee-compile, v0.13.0
docblockr, v0.6.3
git-tab-status, v1.7.0
language-diff, v0.3.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
project-manager, v1.15.5
save-session, vundefined
seti-syntax, v0.3.3
seti-ui, v0.6.3
vim-mode, v0.44.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report. I'm closing this in favor of #642 even though that issue is newer, because it has the default title, which allows the issue to be automatically shown to other people who experience the same issue.
