### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keystrokeForKeyboardEvent' of undefined

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/vim-mode#635]
[Enter steps to reproduce below:]

1. Run atom with `atom --one`
2. Type a numeric repeat prefix before a command

**Atom Version**: 0.195.0-ad67a56 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.44.0

### Stack Trace

Uncaught TypeError: Cannot read property 'keystrokeForKeyboardEvent' of undefined

```
At /Users/maxbrunsfeld/github/vim-mode/lib/vim-state.coffee:483

TypeError: Cannot read property 'keystrokeForKeyboardEvent' of undefined
  at VimState.module.exports.VimState.repeatPrefix (/Users/maxbrunsfeld/github/vim-mode/lib/vim-state.coffee:483:31)
  at atom-text-editor.registerCommands.repeat-prefix (/Users/maxbrunsfeld/github/vim-mode/lib/vim-state.coffee:66:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:50.2.0 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:49.6.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:49.6.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:47.5.0 core:move-down (atom-text-editor.editor.mini)
     -0:47.1.0 core:confirm (atom-text-editor.editor.mini)
     -0:47.1.0 blur (atom-text-editor.editor.mini)
  3x -0:31.2.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -0:29.6.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  8x -0:16.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:16 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:04.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:03.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:02.9.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.4.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:00.2.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "coffee-compile",
      "autocomplete"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.4.3
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
jasmine-runner, v0.0.0
language-asciidoc, v0.11.1
language-rust, v0.4.3
linter, v0.12.1
linter-clang, v2.25.1
vim-mode, v0.44.0

# Dev
vim-mode, v0.44.0
```

**Comment by ddelrio1986** [comment]
This is happening for me as well.
