### ISSUE TITLE
Cannot read property 'eachEditorView' of undefined

### ISSUE THREAD

**Issue by speric** [atom/vim-mode#637]
Opened atom to read a CSV file.

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.1
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.7.0

### Stack Trace

Failed to activate the vim-mode package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
    at Object.module.exports.activate (/Users/efarkas/.atom/packages/vim-mode/lib/vim-mode.coffee:8:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "tomorrow"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
tomorrow, v0.2.0
vim-mode, v0.7.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
You're using a very old version of `vim-mode`. Upgrading to the latest (`0.45.0`) should fix this problem.

**Comment by speric** [comment]
Thanks!
