### ISSUE TITLE
Unable to drag file from one pane to another

### ISSUE THREAD

**Issue by reneklacan** [atom/vim-mode#640]
1. Open 2 panes
2. Open 1 file in each pane
3. Try to drag file from one to pane to another

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.21.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setInputEnabled' of null

```
At /Users/rene/.atom/packages/vim-mode/lib/vim-state.coffee:362

TypeError: Cannot read property 'setInputEnabled' of null
  at VimState.module.exports.VimState.deactivateInsertMode (/Users/rene/.atom/packages/vim-mode/lib/vim-state.coffee:362:29)
  at VimState.module.exports.VimState.activateCommandMode (/Users/rene/.atom/packages/vim-mode/lib/vim-state.coffee:332:6)
  at new VimState (/Users/rene/.atom/packages/vim-mode/lib/vim-state.coffee:39:8)
  at /Users/rene/.atom/packages/vim-mode/lib/vim-mode.coffee:26:22
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:271:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:328:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:370:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:357:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:415:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:576:18)
  at TabBarView.module.exports.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:499:23)
  at space-pen-ul.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -2:39.2.0 core:backspace (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:36.8.0 core:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:35.5.0 core:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:35.3.0 core:move-right (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:34.9.0 core:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:28.2.0 core:move-right (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:27.5.0 editor:newline (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:26.8.0 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:25.8.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:26.2.0 fuzzy-finder:toggle-file-finder (div.rspec.rspec-console)
     -0:24.3.0 core:move-down (atom-text-editor.editor.mini)
     -0:23.2.0 core:confirm (atom-text-editor.editor.mini)
     -0:11.3.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.7.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:04.2.0 core:move-down (atom-text-editor.editor.mini)
     -0:03.9.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.17.1
atom-rails, v0.3.4
rspec, v0.3.0
ruby-slim, v0.2.0
term2, v0.9.5
vim-mode, v0.21.0

# Dev
No dev packages
```

**Comment by reneklacan** [comment]
I probably had a very old version... my bad ;)
