### ISSUE TITLE
Error: Failed to execute 'remove' on 'Element':

### ISSUE THREAD

**Issue by LukeMauldin** [atom/vim-mode#642]
**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.45.0
### Stack Trace

Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Users/lmauldin/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8

Error: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at /Users/lmauldin/.atom/packages/vim-mode/lib/view-models/view-model.coffee:8:43
  at Emitter.module.exports.Emitter.emit (/Users/lmauldin/.atom/packages/vim-mode/node_modules/event-kit/lib/emitter.js:71:11)
  at VimState.module.exports.VimState.pushOperations (/Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:207:18)
  at atom-text-editor.commands.(anonymous function) (/Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:190:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
  2x -0:07.4.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:06.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:06.4.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.1.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.1.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.5.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.8.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:02.2.0 vim-mode:change (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.6.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:01.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.1.0 vim-mode:till (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:01.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.1.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:01.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:01.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "grunt-runner",
      "linter-phpcs",
      "gocode",
      "go-oracle",
      "atom-ctags",
      "transient-emacs"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atomatigit, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
command-logger, v0.23.0
dash, v1.1.1
editor-stats, v0.17.0
editorconfig, v1.0.0
git-log, v0.3.0
go-plus, v3.3.9
jumpy, v2.0.6
language-laravel-blade, v0.2.0
linter-jshint, v0.1.2
linter-php, v0.0.12
pain-split, v1.3.1
script, v2.19.0
symbols-tree-view, v0.9.2
tabs-to-spaces, v0.9.2
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
