### ISSUE TITLE
<number> gg blowing up!

### ISSUE THREAD

**Issue by ozkar99** [atom/vim-mode#648]
[Enter steps to reproduce below:]

1. Open any file with vim-mode installed.
2.  Type any number (23)

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.45.0

### Stack Trace

Uncaught TypeError: Cannot read property 'keystrokeForKeyboardEvent' of undefined

```
At /Users/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:485

TypeError: Cannot read property 'keystrokeForKeyboardEvent' of undefined
  at VimState.module.exports.VimState.repeatPrefix (/Users/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:485:31)
  at atom-text-editor.registerCommands.repeat-prefix (/Users/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:66:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -1:24.2.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.command-mode)
     -1:00.4.0 application:hide (atom-text-editor.editor.vim-mode.command-mode)
     -0:53.4.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
 12x -0:32 core:backspace (atom-text-editor.editor.mini)
     -0:26.4.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:26.4.0 core:cancel (atom-text-editor.editor.mini)
     -0:10.6.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:00.8.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by ozkar99** [comment]
I am removing this issue, since i cant re-produce it anymore (and was hoping i could actually fix it by myself), After a reboot of my computer realized the issue was gone...
