### ISSUE TITLE
Uncaught TypeError: Cannot read property 'displayBuffer' of undefined

### ISSUE THREAD

**Issue by LukeMauldin** [atom/vim-mode#665]
1. In normal mode type 'dd' to delete line

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.46.0
### Stack Trace

Uncaught TypeError: Cannot read property 'displayBuffer' of undefined

```
At /Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:256

TypeError: Cannot read property 'displayBuffer' of undefined
  at SymbolStore.module.exports.SymbolStore.getTokenizedLines (/Users/lmauldin/.atom/packages/autocomplete-plus/lib/symbol-store.coffee:209:11)
  at SymbolStore.module.exports.SymbolStore.operateOnTokensInBufferRange (/Users/lmauldin/.atom/packages/autocomplete-plus/lib/symbol-store.coffee:175:23)
  at SymbolStore.module.exports.SymbolStore.removeTokensInBufferRange (/Users/lmauldin/.atom/packages/autocomplete-plus/lib/symbol-store.coffee:172:6)
  at /Users/lmauldin/.atom/packages/autocomplete-plus/lib/symbol-provider.coffee:70:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:488:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:461:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:564:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:560:37)
  at Delete.execute (/Users/lmauldin/.atom/packages/vim-mode/lib/operators/general-operators.coffee:98:19)
  at VimState.module.exports.VimState.processOpStack (/Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:259:23)
  at VimState.module.exports.VimState.processOpStack (/Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:251:10)
  at VimState.module.exports.VimState.pushOperations (/Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:220:8)
  at atom-text-editor.commands.(anonymous function) (/Users/lmauldin/.atom/packages/vim-mode/lib/vim-state.coffee:192:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -0:17.4.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:17.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:16.3.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:15.5.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:14.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:14.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:13.6.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:13.4.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:11.7.0 core:close (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 13x -0:11.7.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:05.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:05.8.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:04.2.0 blur (atom-text-editor.editor.mini.is-focused)
 13x -0:03.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:01.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "grunt-runner",
      "gocode",
      "go-oracle",
      "atom-ctags",
      "transient-emacs",
      "linter-phpcs"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atomatigit, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.14.2
autocomplete-snippets, v1.6.1
command-logger, v0.23.0
editor-stats, v0.17.0
editorconfig, v1.0.0
git-log, v0.3.0
go-plus, v3.3.10
jumpy, v2.0.6
language-laravel-blade, v0.2.0
linter, v0.12.2
linter-jshint, v0.1.4
linter-php, v0.0.12
pain-split, v1.4.0
script, v2.23.0
symbols-tree-view, v0.9.2
tabs-to-spaces, v0.10.0
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
@benogle this seems like it might be an autocomplete-plus issue.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
