### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by drakmail** [atom/vim-mode#687]
[Enter steps to reproduce below:]
1. In visual mode in file with lines more that two (like "\n123") put cursor at end of any not first line
2. 10 times press "9"
3. 10 times press "0"
4. Wait 10 seconds
5. Press any key (I'm tested with key "h")
6. Get error Uncaught RangeError: Invalid array length :smile: 

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.49.0
### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Users/drakmail/.atom/packages/vim-mode/lib/vim-state.coffee:257

RangeError: Invalid array length
  at Object._.times (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:1118:28)
  at MoveLeft.moveCursor (/Users/drakmail/.atom/packages/vim-mode/lib/motions/general-motions.coffee:145:7)
  at MoveLeft.Motion.execute (/Users/drakmail/.atom/packages/vim-mode/lib/motions/general-motions.coffee:35:8)
  at Repeat.Prefix.execute (/Users/drakmail/.atom/packages/vim-mode/lib/prefixes.coffee:21:31)
  at VimState.module.exports.VimState.processOpStack (/Users/drakmail/.atom/packages/vim-mode/lib/vim-state.coffee:260:23)
  at VimState.module.exports.VimState.processOpStack (/Users/drakmail/.atom/packages/vim-mode/lib/vim-state.coffee:252:10)
  at VimState.module.exports.VimState.pushOperations (/Users/drakmail/.atom/packages/vim-mode/lib/vim-state.coffee:221:8)
  at atom-text-editor.commands.(anonymous function) (/Users/drakmail/.atom/packages/vim-mode/lib/vim-state.coffee:193:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
  5x -1:06.5.0 blur (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
 10x -1:02.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  9x -0:58 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:46.4.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:45 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:45 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:43.9.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  9x -0:42.9.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  9x -0:40.6.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:27.9.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:24.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:22.6.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:22.2.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  9x -0:21.4.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  9x -0:18.3.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:00.7.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "ruby-slim"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.6.3
chester-atom-syntax, v0.1.1
emmet, v2.3.10
slim-language, v2.2.0
trailing-spaces, v0.3.0
vim-mode, v0.49.0

# Dev
No dev packages
```

**Comment by sorear** [comment]
The same error shows up after `10|h`.  I would expect `10|` to go to column 10.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
