### ISSUE TITLE
undo after ex-mode's replace raises TypeError

### ISSUE THREAD

**Issue by atsepkov** [atom/vim-mode#699]
Not sure if this is a bug in ex-mode (leaving the system in a bad state) or vim-mode, but here is the behavior I'm seeing:

When performing a search/replace command from ex-mode, followed by undo, i.e:

```
:,+5s/before/after/
u
```

Undo correctly undoes the changes done by ex-mode, but also throws the following error:

```
Uncaught TypeError: Cannot read property '0' of undefined
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:203
```

Full stack trace:

TypeError: Cannot read property '0' of undefined
  at MarkerStore.module.exports.MarkerStore.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:203:35)
  at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:711:33)
  at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1137:19)
  at VimState.module.exports.VimState.undo (/Users/alexander.tsepkov/.atom/packages/vim-mode/lib/vim-state.coffee:235:13)
  at atom-text-editor.registerCommands.undo (/Users/alexander.tsepkov/.atom/packages/vim-mode/lib/vim-state.coffee:70:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

**Comment by bronson** [comment]
Dupes: #703, https://github.com/lloeki/ex-mode/issues/57

Hopefully https://github.com/lloeki/ex-mode/pull/59 lands soon.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
