### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/vim-mode#702]
1. Select some text.
2. Delete it.

**Atom Version**: 0.210.0-6282e7e
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.53.0
### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At /Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-state.coffee:263

TypeError: Cannot read property 'openScopes' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:589:49)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:383:115)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:516:21)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:633:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:560:37)
  at Delete.execute (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/operators/general-operators.coffee:98:19)
  at VimState.module.exports.VimState.processOpStack (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-state.coffee:266:23)
  at VimState.module.exports.VimState.processOpStack (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-state.coffee:258:10)
  at VimState.module.exports.VimState.pushOperations (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-state.coffee:224:8)
  at atom-text-editor.commands.(anonymous function) (/Users/maxbrunsfeld/.atom/packages/vim-mode/lib/vim-state.coffee:196:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -1:01.1.0 find-and-replace:show (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:59.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:58.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:57.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:57.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:57.7.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:37.9.0 pane:show-item-2 (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:37.5.0 pane:show-item-3 (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:37.1.0 pane:show-item-2 (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:22 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:21.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:21.8.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:21.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:00.9.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:00.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true
  }
}
```
### Installed Packages

``` coffee
# User
asciidoc-preview, v0.5.1
language-asciidoc, v0.11.1
language-latex, v0.6.1
language-rust, v0.4.3
latex, v0.24.1
linter, v0.12.7
linter-clang, v2.26.0
linter-xmllint, v0.0.6
vim-mode, v0.53.0

# Dev
find-and-replace, v0.172.0
vim-mode, v0.53.0
```

**Comment by maxbrunsfeld** [comment]
```javascript
tokenizedBuffer = atom.workspace.getActiveEditor().displayBuffer.tokenizedBuffer;
tokenizedBuffer.tokenizedLines.length // 234
tokenizedBuffer.tokenizedLines[164]   // undefined
```

It looks like there are lines missing from the `TokenizedBuffer`. Maybe these lines were initially folded when I opened the file?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
