### ISSUE TITLE
Failed to activate the vim-mode package

### ISSUE THREAD

**Issue by ozkar99** [atom/vim-mode#704]
[Enter steps to reproduce below:]

1. Enable extension.

**Atom Version**: 0.196.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.53.0

### Stack Trace

Failed to activate the vim-mode package

```
At undefined is not a function

TypeError: undefined is not a function
  at getChangesSinceCheckpoint (/home/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:556:6)
  at VimState.module.exports.VimState.deactivateInsertMode (/home/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:409:15)
  at VimState.module.exports.VimState.activateCommandMode (/home/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:375:6)
  at new VimState (/home/ozkar/.atom/packages/vim-mode/lib/vim-state.coffee:44:8)
  at /home/ozkar/.atom/packages/vim-mode/lib/vim-mode.coffee:21:22
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:267:9)
  at Object.module.exports.activate (/home/ozkar/.atom/packages/vim-mode/lib/vim-mode.coffee:18:37)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:222:19)
  at /usr/share/atom/resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:434:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:303:19
  at /usr/share/atom/resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:252:27)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -7:07.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
  3x -7:05.4.0 core:backspace (atom-text-editor.editor.mini)
     -7:02.0 core:confirm (atom-text-editor.editor.mini)
 17x -7:00.6.0 core:move-down (atom-text-editor.editor)
     -6:57.6.0 core:backspace (atom-text-editor.editor)
     -6:57.4.0 editor:consolidate-selections (atom-text-editor.editor)
     -6:57.4.0 core:cancel (atom-text-editor.editor)
     -6:56.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -6:55.9.0 editor:newline (atom-text-editor.editor)
     -6:54.3.0 autocomplete-plus:confirm (atom-text-editor.editor)
     -6:51.4.0 core:backspace (atom-text-editor.editor)
  2x -6:49.7.0 core:save (atom-text-editor.editor)
     -0:15.6.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/ozkar/Work"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.7.2
autocomplete-html, v0.7.2
autocomplete-plus, v2.17.3
autocomplete-ruby, v0.1.0
language-haml, v0.21.0
tabs-to-spaces, v0.10.0
tree-view-open-files, v0.2.4
vim-mode, v0.53.0

# Dev
No dev packages
```

# Additional Comments

This started happening since the last update, the previous version had no issues.

**Comment by ozkar99** [comment]
i think this is related: https://github.com/atom/vim-mode/commit/793dfa2e10bc6b3fd33fbcedcd92d644499d6a19

ill update to atom 0.2 and test

**Comment by ozkar99** [comment]
No problems with atom 0.2.x

Closing the issue.
