### ISSUE TITLE
Failed to activate the vim-mode package

### ISSUE THREAD

**Issue by AnuchitPrasertsang** [atom/vim-mode#708]
ndefined is not a function
Hide Stack Trace
TypeError: undefined is not a function
    at getChangesSinceCheckpoint (/home/nong/.atom/packages/vim-mode/lib/vim-state.coffee:1095:26)
    at VimState.module.exports.VimState.deactivateInsertMode (/home/nong/.atom/packages/vim-mode/lib/vim-state.coffee:916:17)
    at VimState.module.exports.VimState.activateCommandMode (/home/nong/.atom/packages/vim-mode/lib/vim-state.coffee:871:12)
    at new VimState (/home/nong/.atom/packages/vim-mode/lib/vim-state.coffee:73:14)
    at /home/nong/.atom/packages/vim-mode/lib/vim-mode.coffee:28:22
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:267:9)
    at Object.module.exports.activate (/home/nong/.atom/packages/vim-mode/lib/vim-mode.coffee:22:43)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:222:19)
    at /usr/share/atom/resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)

**Comment by 50Wliu** [comment]
Hi @AnuchitPrasertsang, what Atom version is this?

**Comment by maxbrunsfeld** [comment]
Yeah, it looks like upgrading Atom will fix this problem. Let us know what happens when you upgrade Atom, @AnuchitPrasertsang.

**Comment by matsilva** [comment]
@maxbrunsfeld I was running into this issue using Atom 0.188.0
OS is Ubuntu 14.0.4, I needed to manually install the latest version of Atom, which brought me out of the stone age to version 1.0.6. Everything works fine now.

**Comment by maxbrunsfeld** [comment]
:+1:

**Comment by asfktz** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.1


### Stack Trace

Failed to activate the vim-mode package

```
At this.editor.buffer.getChangesSinceCheckpoint is not a function

TypeError: this.editor.buffer.getChangesSinceCheckpoint is not a function
    at VimState.module.exports.VimState.deactivateInsertMode (/Users/asafkatz/.atom/packages/vim-mode/lib/vim-state.coffee:456:30)
    at VimState.module.exports.VimState.activateNormalMode (/Users/asafkatz/.atom/packages/vim-mode/lib/vim-state.coffee:392:6)
    at new VimState (/Users/asafkatz/.atom/packages/vim-mode/lib/vim-state.coffee:45:8)
    at /Users/asafkatz/.atom/packages/vim-mode/lib/vim-mode.coffee:21:22
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:307:9)
    at Object.module.exports.activate (/Users/asafkatz/.atom/packages/vim-mode/lib/vim-mode.coffee:18:37)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:693:36
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:458:15
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:12.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.9.3
build, v0.62.0
language-ini, v1.16.0
linter, v1.11.4
linter-gcc, v0.6.14
platformio-ide, v1.2.1
platformio-ide-terminal, v2.0.9
tool-bar, v0.4.0
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by stefanvlaski** [comment]
Update your Atom version and you should be good to go. `Buffer.getChangesSinceCheckpoint` was only recently added to the core (it's in 1.7.3 for sure, don't know about 1.7.2). In vim-mode, this function was used to be replace a broken method and fix #1006 as well as #1010 through #1020, released in vim-mode 0.65.1.

Maybe the appropriate version of Atom can be added as a dependency?

**Comment by Vinnl** [comment]
Something like that would probably be a good idea. Since it's often easier to update plugins than the entire application, this probably breaks for relatively many people.

**Comment by technoobish** [comment]
<p>
Breaks for anyone who hasn't installed 1.7.3 I presume?
</p>

**Comment by plbowers** [comment]
This issue comes up when event-kit isn't available as well. 

Fix it by going into your `~/.atom/packages/vim-mode` directory and executing `apm install` to install dependencies.

(I get this error whenever I install vim-mode directly from git so that I can make changes to the source and submit them back as pull requests)
