### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by hggz** [atom/vim-mode#726]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.54.0
### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:204

TypeError: Cannot read property '1' of undefined
  at MarkerStore.module.exports.MarkerStore.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:204:35)
  at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:715:33)
  at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1142:19)
  at VimState.module.exports.VimState.undo (/Users/hugogonzalez/.atom/packages/vim-mode/lib/vim-state.coffee:239:13)
  at atom-text-editor.registerCommands.undo (/Users/hugogonzalez/.atom/packages/vim-mode/lib/vim-state.coffee:71:23)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:13.2.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:13.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:11.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:10.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:08.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:08.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:08.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 vim-mode:undo (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:05.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:02.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.0 vim-mode:undo (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
ex-mode, v0.5.1
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
