### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by lobida** [atom/vim-mode#728]
[Enter steps to reproduce below:]
1. ...press ctrl +n 
2. ...press ctrl +y  

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.54.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\display-buffer.js:996

TypeError: Cannot read property 'getTokenIterator' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.pixelPositionForScreenPosition (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\display-buffer.js:996:59)
  at DisplayBuffer.module.exports.DisplayBuffer.pixelRectForScreenRange (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\display-buffer.js:704:22)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToScreenRange (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\display-buffer.js:643:20)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToScreenPosition (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\display-buffer.js:689:19)
  at TextEditor.module.exports.TextEditor.scrollToScreenPosition (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\text-editor.js:2534:33)
  at ScrollUp.scrollDown (e:\Users\zu-jie.wang\.atom\packages\vim-mode\lib\scroll.coffee:40:13)
  at ScrollUp.execute (e:\Users\zu-jie.wang\.atom\packages\vim-mode\lib\scroll.coffee:30:6)
  at VimState.module.exports.VimState.processOpStack (e:\Users\zu-jie.wang\.atom\packages\vim-mode\lib\vim-state.coffee:266:23)
  at VimState.module.exports.VimState.pushOperations (e:\Users\zu-jie.wang\.atom\packages\vim-mode\lib\vim-state.coffee:224:8)
  at atom-text-editor.commands.(anonymous function) (e:\Users\zu-jie.wang\.atom\packages\vim-mode\lib\vim-state.coffee:196:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\command-registry.js:241:29)
  at e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (e:\Users\zu-jie.wang\Desktop\Atom\resources\app.asar\src\window-event-handler.js:180:20)

```
### Commands

```
     -0:23.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:20.4.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:20.4.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:19.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:19.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:18.7.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:18.7.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:17.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:17.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:17.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:16.1.0 application:new-file (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:16.1.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:12.8.0 vim-mode:scroll-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.2.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by petemill** [comment]
This is happening for me on many (non-insert) operations in vim-mode, usually when you get to the end of a file

**Comment by jacekkopecky** [comment]
@petemill do you have a reliable way to trigger this, please? And what are the versions of your Atom and vim-mode?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
