### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clearSelections' of null

### ISSUE THREAD

**Issue by bradleyflood** [atom/vim-mode#729]
Not sure of reproduction steps yet. Will post if I find out.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.54.0
### Stack Trace

Uncaught TypeError: Cannot read property 'clearSelections' of null

```
At /Users/bradleyflood/.atom/packages/vim-mode/lib/vim-state.coffee:506

TypeError: Cannot read property 'clearSelections' of null
  at VimState.module.exports.VimState.resetCommandMode (/Users/bradleyflood/.atom/packages/vim-mode/lib/vim-state.coffee:506:12)
  at VimState.module.exports.VimState.processOpStack (/Users/bradleyflood/.atom/packages/vim-mode/lib/vim-state.coffee:261:12)
  at VimState.module.exports.VimState.pushOperations (/Users/bradleyflood/.atom/packages/vim-mode/lib/vim-state.coffee:224:8)
  at ViewModel.cancel (/Users/bradleyflood/.atom/packages/vim-mode/lib/view-models/view-model.coffee:15:17)
  at vim-command-mode-input.VimCommandModeInputElement.cancel (/Users/bradleyflood/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:53:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at atom-text-editor.jQuery.event.special.focus.trigger (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4596:11)
  at Object.jQuery.event.trigger (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4316:60)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4901:17)
  at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:374:23)
  at TextEditorView.jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:139:17)
  at TextEditorView.jQuery.fn.extend.trigger [as originalTrigger] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4900:15)
  at TextEditorView.$.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:606:19)
  at TextEditorView.jQuery.fn.(anonymous function) [as focus] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:7487:9)
  at ProjectView.module.exports.SelectListView.focusFilterEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:274:36)
  at ProjectView.module.exports.FuzzyFinderView.show (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:351:19)
  at ProjectView.module.exports.ProjectView.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/project-view.js:88:21)
  at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:24:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:51.5.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:35.1.0 application:new-file (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:34.2.0 core:save (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.6.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.6.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.5.0 vim-mode:replace (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:06.2.0 blur (atom-text-editor.editor.mini.is-focused)
  2x -0:06.1.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.4.0 vim-mode:find (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:04.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:04.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.0 vim-mode:find (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:04.0 blur (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:03.2.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:02.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.mini.is-focused)
     -0:02.0 blur (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "vim-mode": {}
}
```
### Installed Packages

``` coffee
# User
emmet, v2.3.11
linter, v1.1.0
minimap, v4.10.1
project-manager, v1.15.10
remote-sync, v3.1.2
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
