### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by codykrieger** [atom/vim-mode#759]
Atom: v1.0.1
vim-mode: v0.55.0

I was fiddling with a selection inside of a set of backticks in a ruby file when I saw this (something something (``vi` ``). I haven't been able to reproduce it with some (extremely) limited testing.

Atom originally pointed me at #705, which was already closed.

Backtrace:

```
TypeError: undefined is not a function
  at VimState.module.exports.VimState.processOpStack (/Users/cjk/.atom/packages/vim-mode/lib/vim-state.coffee:268:23)
  at VimState.module.exports.VimState.pushOperations (/Users/cjk/.atom/packages/vim-mode/lib/vim-state.coffee:226:8)
  at ViewModel.confirm (/Users/cjk/.atom/packages/vim-mode/lib/view-models/view-model.coffee:11:15)
  at vim-command-mode-input.VimCommandModeInputElement.confirm (/Users/cjk/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:46:16)
  at /Users/cjk/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:36:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:468:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:736:29
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:778:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1151:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:772:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2017:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1987:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:770:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:733:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:444:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

**Comment by bzx** [comment]
+1 on latest Atom & OSX

**Comment by jacekkopecky** [comment]
@bzx - do you have steps to reproduce this, by any chance? And what is your vim-mode version, please?

**Comment by bzx** [comment]
@jacekkopecky 

vim-mode latest, which is: 0.57.0

repro steps:
- open HTML document, with some code in it
- focus cursor on any tag that has some text inside, for example:
```
<p class="something">i want to select text inside tags</p>
```
- toggle command console (cmd+P)
- find and select this option "Vim Mode: Select inside tags" 
- the error appears and it tells me that it was already filed, which points me to #705, but then only this bug is open. 

thanks!

**Comment by jacekkopecky** [comment]
Confirmed reproduced, thank you, that'll make it much easier to fix.

**Comment by bzx** [comment]
radose ;) zdravim ahoj!

**Comment by mleeds95** [comment]
I think I'm very close to fixing this issue. In vim, text object selection is only legal after an operator or in visual mode, but vim-mode never checks for those conditions. So I think in lib/vim-state.coffee in either `pushOperations()` or `processOpStack()` we should check if we're not in `visual` mode but have a `TextObject` not preceded by an operator. Without the check, the code attempts to call `.execute()` when there's only a `.select()` instead.

**Comment by mleeds95** [comment]
This makes the second `instanceof` check on [this line](https://github.com/atom/vim-mode/blob/master/lib/vim-state.coffee#L224) unnecessary. Should we take it out?
