### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editors' of undefined

### ISSUE THREAD

**Issue by revspringjake** [atom/vim-mode#789]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.55.0
### Stack Trace

Uncaught TypeError: Cannot read property 'editors' of undefined

```
At /Users/jakedanforth/.atom/packages/vim-mode/lib/vim-state.coffee:257

TypeError: Cannot read property 'editors' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:115:54
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:518:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:516:21)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:633:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:586:37)
  at Change.execute (/Users/jakedanforth/.atom/packages/vim-mode/lib/operators/input.coffee:104:21)
  at VimState.module.exports.VimState.processOpStack (/Users/jakedanforth/.atom/packages/vim-mode/lib/vim-state.coffee:260:23)
  at VimState.module.exports.VimState.processOpStack (/Users/jakedanforth/.atom/packages/vim-mode/lib/vim-state.coffee:252:10)
  at VimState.module.exports.VimState.pushOperations (/Users/jakedanforth/.atom/packages/vim-mode/lib/vim-state.coffee:221:8)
  at atom-text-editor.commands.(anonymous function) (/Users/jakedanforth/.atom/packages/vim-mode/lib/vim-state.coffee:193:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
  4x -3:04.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:56.9.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  7x -2:51.7.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 48x -2:50.5.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:44.7.0 core:delete (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:39.2.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:24.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-monokai.theme-unity-ui)
     -0:10.1.0 core:close (div.settings-view.pane-item)
  7x -0:08.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -0:06.6.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:05.9.0 vim-mode:move-to-next-whole-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 11x -0:04.3.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.8.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.7.0 vim-mode:select-inside-word (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:00.9.0 vim-mode:change (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "relative-numbers",
      "welcome",
      ".bin"
    ],
    "themes": [
      "unity-ui",
      "seti-monokai"
    ]
  },
  "vim-mode": {
    "useSmartcaseForSearch": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-typescript, v5.0.29
color-picker, v2.0.11
highlight-selected, v0.10.1
linter, v1.2.4
linter-jshint, v1.1.2
linter-tslint, v0.2.3
seti-monokai, v0.3.1
unity-ui, v2.0.11
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
