### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEmpty' of undefined

### ISSUE THREAD

**Issue by Bondza** [atom/vim-mode#803]
This occurs when I try to delete a line using dd, but not in all buffers. I also get https://github.com/atom/bracket-matcher/issues/102 whenever I try to edit the file in insert mode.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.57.0
### Stack Trace

Uncaught TypeError: Cannot read property 'isEmpty' of undefined

```
At /Users/Bondza/.atom/packages/vim-mode/lib/vim-state.coffee:272

TypeError: Cannot read property 'isEmpty' of undefined
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:108:42)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1595:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1554:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:404:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:64:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:631:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:785:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:754:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1151:26)
  at Delete.execute (/Users/Bondza/.atom/packages/vim-mode/lib/operators/general-operators.coffee:89:15)
  at VimState.module.exports.VimState.processOpStack (/Users/Bondza/.atom/packages/vim-mode/lib/vim-state.coffee:275:23)
  at VimState.module.exports.VimState.processOpStack (/Users/Bondza/.atom/packages/vim-mode/lib/vim-state.coffee:267:10)
  at VimState.module.exports.VimState.pushOperations (/Users/Bondza/.atom/packages/vim-mode/lib/vim-state.coffee:233:8)
  at atom-text-editor.commands.(anonymous function) (/Users/Bondza/.atom/packages/vim-mode/lib/vim-state.coffee:205:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:26.7.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:26.7.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:26.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:07.1.0 blur (atom-text-editor.editor.mini.is-focused)
  3x -0:06.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:05.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:04.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:03.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
  2x -0:03.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.7.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  5x -0:01.2.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.7.1
emmet, v2.3.12
ex-mode, v0.6.2
javascript-snippets, v1.0.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Does this happen if you disabled `emmet`?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
