### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by Foxly1990** [atom/vim-mode#822]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Ubuntu 14.04.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.57.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /opt/atom/resources/app.asar/src/display-buffer.js:998

TypeError: Cannot read property 'getTokenIterator' of undefined
    at DisplayBuffer.module.exports.DisplayBuffer.pixelPositionForScreenPosition (/opt/atom/resources/app.asar/src/display-buffer.js:998:59)
    at DisplayBuffer.module.exports.DisplayBuffer.pixelRectForScreenRange (/opt/atom/resources/app.asar/src/display-buffer.js:706:22)
    at DisplayBuffer.module.exports.DisplayBuffer.scrollToScreenRange (/opt/atom/resources/app.asar/src/display-buffer.js:645:20)
    at DisplayBuffer.module.exports.DisplayBuffer.scrollToScreenPosition (/opt/atom/resources/app.asar/src/display-buffer.js:691:19)
    at TextEditor.module.exports.TextEditor.scrollToScreenPosition (/opt/atom/resources/app.asar/src/text-editor.js:2577:33)
    at ScrollUp.scrollDown (/home/ruslan/.atom/packages/vim-mode/lib/scroll.coffee:91:26)
    at ScrollUp.execute (/home/ruslan/.atom/packages/vim-mode/lib/scroll.coffee:76:19)
    at VimState.module.exports.VimState.processOpStack (/home/ruslan/.atom/packages/vim-mode/lib/vim-state.coffee:817:32)
    at VimState.module.exports.VimState.pushOperations (/home/ruslan/.atom/packages/vim-mode/lib/vim-state.coffee:767:28)
    at atom-text-editor.commands.(anonymous function) (/home/ruslan/.atom/packages/vim-mode/lib/vim-state.coffee:733:26)
```
### Commands

```
  2x -2:28.2.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:55.9.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:33.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:25.2.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:24.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -1:20.3.0 core:delete (atom-text-editor.editor.mini.is-focused)
  3x -1:18.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:14.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.7.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:03.1.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:33.6.0 find-and-replace:select-next (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:31.9.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:25.7.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.3.0 core:undo (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.5.0 vim-mode:scroll-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.11
emmet, v2.3.12
minimap, v4.12.2
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report. Can you reproduce this consistently? Does it happen if you disable `emmet` and `minimap`?

**Comment by sejjiin** [comment]
Happens consistently for me if I `ctrl-y` at the top of a new empty file. Key Binding Resolver has `vim-mode:scroll-up` and `core:redo` checked. I don't have `emmet` or `minimap`.
