### ISSUE TITLE
Vim-mode not working

### ISSUE THREAD

**Issue by RongxinZhang** [atom/vim-mode#828]
**System:**
- Mac OSX 10.9.5
- Atom 0.152.0

**Reproduce:***
- Starting VIM and pressing ESC

**Message:**
``` js
Failed to activate package named 'vim-mode' TypeError: undefined is not a function
  at getChangesSinceCheckpoint (/Users/rongxinz/.atom/packages/vim-mode/lib/vim-state.coffee:679:6)
  at VimState.module.exports.VimState.deactivateInsertMode (/Users/rongxinz/.atom/packages/vim-mode/lib/vim-state.coffee:465:15)
  at VimState.module.exports.VimState.activateNormalMode (/Users/rongxinz/.atom/packages/vim-mode/lib/vim-state.coffee:399:6)
  at new VimState (/Users/rongxinz/.atom/packages/vim-mode/lib/vim-state.coffee:50:8)
  at /Users/rongxinz/.atom/packages/vim-mode/lib/vim-mode.coffee:21:22
  at Workspace.module.exports.Workspace.observeTextEditors (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:273:9)
  at Object.module.exports.activate (/Users/rongxinz/.atom/packages/vim-mode/lib/vim-mode.coffee:18:37)
  at Package.module.exports.Package.activateNow (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package.js:227:27)
  at /Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:404:21)
  at PackageManager.module.exports.PackageManager.activatePackages (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:393:14)
  at PackageManager.module.exports.PackageManager.activate (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:379:19)
  at Atom.module.exports.Atom.startEditorWindow (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/atom.js:584:21)
  at Object.<anonymous> (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/static/index.js:59:25)
 /Users/rongxinz/Downloads/Atom.app/Contents/Resources/app/src/package.js:232
Window load time: 1178ms index.js:64
Uncaught TypeError: undefined is not a function 
```

**Comment by maxbrunsfeld** [comment]
This is because you're using a pretty old version of Atom. Upgrading Atom should fix the problem.

**Comment by RongxinZhang** [comment]
@maxbrunsfeld yea. that. solved. it. lol
