### ISSUE TITLE
Replacing with special characters (`, ´, ^) in normal mode

### ISSUE THREAD

**Issue by Protossoario** [atom/vim-mode#834]
1. Open any text file.
2. Enter normal mode (press ESC).
3. Press `r` to replace a character.
4. Try to insert a special character such as ò, á, ê, etc.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:760

TypeError: Cannot read property 'split' of null
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:459:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:740:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:782:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1155:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:776:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2019:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1993:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:774:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:737:19)
```

### Commands

```
     -0:40.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:34.4.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:33.3.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:29 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:28.5.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:26.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25.5.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:25.1.0 vim-mode:replace (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:25.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:24.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:22.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:22.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:12.1.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:02.9.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.9.0 vim-mode:replace (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:01.9.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "tabLength": 4,
    "softWrapHangingIndent": 4,
    "showIndentGuide": true,
    "softWrap": true,
    "preferredLineLength": 120,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.1
atom-jade, v0.3.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
language-haml, v0.21.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by jacekkopecky** [comment]
duplicate of #791, I suspect.

**Comment by jacekkopecky** [comment]
The fix hasn't been released in a vim-mode release yet, I'm afraid.

**Comment by izuzak** [comment]
@jacekkopecky Ahh, interesting. Should https://github.com/atom/vim-mode/issues/791 be reopened then?

**Comment by jacekkopecky** [comment]
No, the fix is merged, just waiting to be released

**Comment by maxbrunsfeld** [comment]
Oh, I'm sorry for delaying that when this is causing people pain. Pushing out v0.60 now.
