### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bobowolf** [atom/vim-mode#860]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: linux 4.2.0-040200-generic
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.60.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/guanghw/.atom/packages/vim-mode/lib/vim-state.coffee:677

TypeError: undefined is not a function
  at getChangesSinceCheckpoint (/home/guanghw/.atom/packages/vim-mode/lib/vim-state.coffee:677:6)
  at VimState.module.exports.VimState.deactivateInsertMode (/home/guanghw/.atom/packages/vim-mode/lib/vim-state.coffee:454:15)
  at VimState.module.exports.VimState.activateNormalMode (/home/guanghw/.atom/packages/vim-mode/lib/vim-state.coffee:390:6)
  at atom-text-editor.registerCommands.activate-normal-mode (/home/guanghw/.atom/packages/vim-mode/lib/vim-state.coffee:66:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:00.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "vim-mode": {}
}
```

### Installed Packages

```coffee
# User
vim-mode, v0.60.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please update Atom to 1.0.11.  Then, if you experience this exception again, please add some reproduction steps to the issue :).  Thanks.

**Comment by bobowolf** [comment]
It works. Thank you
