### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

### ISSUE THREAD

**Issue by wvengen** [atom/vim-mode#863]
When I press a number in the edit area, an exception is thrown.

**Atom Version**: 1.0.12-bc68056
**System**: Ubuntu 15.04
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.60.0

### Stack Trace

Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

```
At ~/bin/local/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:345

TypeError: Cannot read property 'keyIdentifier' of undefined
  at keyForKeyboardEvent (~/bin/local/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:345:26)
  at exports.keystrokeForKeyboardEvent (~/bin/local/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:162:11)
  at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/bin/local/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:385:14)
  at VimState.module.exports.VimState.repeatPrefix (~/.atom/packages/vim-mode/lib/vim-state.coffee:588:33)
  at atom-text-editor.registerCommands.repeat-prefix (~/.atom/packages/vim-mode/lib/vim-state.coffee:71:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/bin/local/atom/share/atom/resources/app.asar/src/command-registry.js:240:29)
  at ~/bin/local/atom/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/bin/local/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/bin/local/atom/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (~/bin/local/atom/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
 16x -1:23.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:22.2.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:18.8.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:18.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:18.5.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:18.3.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:18.2.0 vim-mode:delete-to-last-character-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -1:17.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:01.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:00.6.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:00.3.0 vim-mode:move-to-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:58.5.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:58.1.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  9x -0:57.9.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.6.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.2.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "metrics",
      "linter-erb",
      "linter-haml",
      "linter-pylint",
      "linter-rubocop"
    ],
    "projectHome": "~/dev",
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
Handlebars, v1.2.1
Stylus, v1.2.1
atom-beautify, v0.28.12
atom-ctags, vundefined
file-icons, v1.6.9
git-blame-plus, v0.4.6
language-docker, v1.1.3
language-haml, v0.21.0
linter, v1.5.1
linter-csslint, v1.0.5
linter-js-yaml, v1.1.2
linter-jshint, v1.2.0
linter-ruby, v1.1.1
linter-shellcheck, v1.0.1
linter-stylint, v2.0.1
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
minimap, v4.13.3
pigments, v0.15.0
react, v0.12.9
ruby-slim, v0.2.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?  In addition, if it only happens on one file, can you please share that file as a Gist and upload it here?  Thanks.

**Comment by wvengen** [comment]
Safe mode doesn't show this behaviour (and vim-mode is absent). In normal mode, it happens with any file I've encountered.

**Comment by 50Wliu** [comment]
Ugh, I keep forgetting that safe mode also disables Vim Mode...sorry about that.

**Comment by LegNeato** [comment]
Just hit this too, let me know if you need any help debugging.

**Comment by LegNeato** [comment]
Appears to happen when pressing a number (for example, `:1 yy`)

**Comment by kirkonrails** [comment]
+1

**Comment by damassi** [comment]
This just happened to me as well, most noticeably when I try something like `30G`. The only causal event that I can think of was updating XCode command line tools (and XCode) to the latest via the default OSX update process... Nothing new other than that.

**Comment by rbvea** [comment]
+1

**Comment by t9md** [comment]
Number prefix uses keyboard event. And this event seem to be undefined in some platform.
I hit this issue when I run spec via travis-CI for my forked vim-mode. This even happen for commit in the past.
@maxbrunsfeld Could you retry spec for newest commit in the past from travis-CI dahboard?

**Comment by medifle** [comment]
Atom@1.0.13
OSX@10.10.5

Same bug.
Every time I hit a number like `3j`, it throws this error.

**Comment by ianlofs** [comment]
+1 
Atom@1.0.12
OSX@10.10.4

**Comment by lyweiwei** [comment]
+1
Atom@1.0.13
Windows Server 2012 R2

Repros when I hit "+ trying to copy a word to clipboard.

**Comment by lyweiwei** [comment]
Just did some investigation, this seems to be a bug introduced by commit https://github.com/atom/atom/commit/e3f9074f4a98f15a4436a79a2209e2fdece85dd4

As Atom no longer using the originalEvent as prototype of the CustomEvent, the originalEvent member is lost.

**Comment by davepies** [comment]
+1

Atom@1.0.13
OSX@10.11

**Comment by dcalhoun** [comment]
This bug appears for me when attempting to use registers. Commands like...

- `"ayy`
- `"ap`
- `"Bdw`

**Comment by stefan-moraru** [comment]
+1

atom: 1.0.13
vim-mode: 0.60.0
osx: 10.10

Please fix this, as it makes vim-mode unusable.

**Comment by RongxinZhang** [comment]
same issue here! lol :dart: 
osx: 10,10.5
vim mode: 0.58.0
atom: 1.0.13

**Comment by SevenITGithub** [comment]
Same here

WIndows 7 64bits
vim mode: 0.60.0
Atom: 1.0.13

**Comment by ismk** [comment]
+1

OSX: 10.10.5
Vim-Mode: 0.60.0
Atom: 1.0.13

**Comment by nathansobo** [comment]
This is fixed with 1.0.14.

**Comment by wvengen** [comment]
I can confirm that it is fixed with 1.0.14. Thanks for fixing this!

**Comment by maxArturo** [comment]
Thanks! Awesome turnaround for the bug fix.

**Comment by thetizzo** [comment]
:+1: Awesome that this was fixed so quickly.  Kudos to all involved.
