### ISSUE TITLE
Uncaught TypeError: this.editorElement.getHeight is not a function

### ISSUE THREAD

**Issue by nightsh** [atom/vim-mode#918]
Within vim-mode, pressing Z-Z to center the current line into the view triggers the mentioned error.
1. Open a file
2. Go anywhere in the file
3. Press Z-Z
4. Receive error, instead of centering the view around current line.

**Atom Version**: 1.1.0-beta.0-ad60d7b
**System**: Debian GNU/Linux
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.63.0
### Stack Trace

Uncaught TypeError: this.editorElement.getHeight is not a function

```
At /home/victor/.atom/packages/vim-mode/lib/scroll.coffee:67

TypeError: this.editorElement.getHeight is not a function
  at ScrollCursorToMiddle.scrollMiddle (/home/victor/.atom/packages/vim-mode/lib/scroll.coffee:67:31)
  at ScrollCursorToMiddle.execute (/home/victor/.atom/packages/vim-mode/lib/scroll.coffee:64:6)
  at VimState.module.exports.VimState.processOpStack (/home/victor/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
  at VimState.module.exports.VimState.pushOperations (/home/victor/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
  at atom-text-editor.commands.(anonymous function) (/home/victor/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  2x -1:16.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:16 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:15.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:14.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:13.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -1:12.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:11.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:10.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:10.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:09.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  5x -1:09.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:02.1.0 vim-mode:scroll-cursor-to-middle-leave (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:00.7.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:00.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
language-blade, v0.16.0
laravel, v0.7.0
laravel-4-snippets, v0.1.0
laravel-snippets, v2.1.0
tabular, v0.1.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
