### ISSUE TITLE
Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

### ISSUE THREAD

**Issue by averrin** [atom/vim-mode#919]
[Enter steps to reproduce below:]

1. Restore after crash

**Atom Version**: 1.3.0-beta1
**System**: Ubuntu 15.10
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.63.0

### Stack Trace

Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280

TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280:55)
    at TextBuffer.module.exports.TextBuffer.undo (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:14)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor.js:1198:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:2094:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:2076:35)
    at TextEditor.module.exports.TextEditor.undo (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1196:12)
    at VimState.module.exports.VimState.undo (/home/user/.atom/packages/vim-mode/lib/vim-state.coffee:252:13)
    at atom-text-editor.registerCommands.undo (/home/user/.atom/packages/vim-mode/lib/vim-state.coffee:73:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:14.3.0 vim-mode:substitute (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
  2x -0:08.2.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:06.4.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.3.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.1.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "accents-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "web-browser",
      "tool-bar-main",
      "atom-jade",
      "spell-check",
      "seti-icons",
      "atom-color-highlight",
      "local-history",
      "project-view",
      "tool-bar",
      "toolbar-basic",
      "background-tips",
      "image-view",
      "language-csharp",
      "linter-tidy",
      "deprecation-cop",
      "linter-python-pyflakes",
      "opened-files",
      "hyperclick",
      "symbol-gen",
      "symbols-view",
      "symbols-tree-view",
      "run-command",
      "devdocs"
    ],
    "excludeVcsIgnoredPaths": false,
    "autoHideMenuBar": true
  },
  "vim-mode": {}
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.0
accents-ui, v1.1.0
api-docs, v0.0.3
atom-ctags, v4.4.0
atom-jinja2, v0.5.0
auto-reveal-in-sidebar, v0.8.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.3
color-picker, v2.0.13
color-picker-service, v0.0.1
color-tabs, v0.1.8
color-tabs-regex, v0.2.3
emmet, v2.3.14
file-icons, v1.6.11
foldername-tabs, v0.1.5
git-hide, v0.1.2
github-notifications, v0.1.1
javascript-snippets, v1.0.0
language-babel, v2.4.1
language-diff, v0.4.0
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
language-lua, v0.9.4
language-nunjucks, v2.0.0
last-cursor-position, v0.9.0
linter, v1.11.0
linter-eslint, v4.0.0
linter-jscs, v3.2.0
linter-jshint, v1.2.1
linter-pep8, v1.0.1
linter-pylama, v0.2.0
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
nerd-treeview, v0.3.1
pigments, v0.18.1
python-iresolve, v0.0.3
python-tools, v0.6.6
quick-highlight, v0.3.7
remember-file-positions, v0.2.0
swackets, v0.7.0
sync-settings, v0.6.0
tidy-tabs, v0.3.0
time-status, v1.1.0
underline-trailing-whitespace, v1.4.0
vim-mode, v0.63.0
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
Also just popped up for me, but I think it's a core issue (atom/atom#9918)
