### ISSUE TITLE
Cannot read property 'prototype' of undefined since update

### ISSUE THREAD

**Issue by kniteli** [atom/vim-mode#939]
[Enter steps to reproduce below:]
1. update vim-mode (or install)
2. enjoy error

**Atom Version**: 1.3.0
**System**: Linux Mint
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.64.0
### Stack Trace

Failed to load the vim-mode package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/roderick/.atom/packages/vim-mode/lib/motions/search-motion.coffee:1:1)
    at /home/roderick/.atom/packages/vim-mode/lib/motions/search-motion.coffee:9:3
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/motions/search-motion.coffee:9:3)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/motions/search-motion.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/motions/index.coffee:2:68)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/motions/index.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/operators/input.coffee:1:11)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/operators/input.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/operators/index.coffee:5:18)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/operators/index.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/vim-state.coffee:7:13)
    at Object.<anonymous> (/home/roderick/.atom/packages/vim-mode/lib/vim-state.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/roderick/Workspace/vim-mode/lib/vim-mode.coffee:4:12)
    at Object.<anonymous> (/home/roderick/Workspace/vim-mode/lib/vim-mode.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:663:34)
    at /opt/atom/resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:516:30)
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  6x -0:38 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:17.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-gooey-syntax"
    ]
  },
  "vim-mode": {
    "useClipboardAsDefaultRegister": true
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-gooey-syntax, v0.2.1
atom-smart-tabs, v0.1.0
atom-tsd, v0.9.0
atom-typescript, v7.14.2
atomize-d, v0.1.0
autocomplete-python, v1.2.3
autocomplete-ruby, v0.1.0
bottom-dock, v0.3.6
git-hide, v0.1.2
gpp-compiler, v1.1.0
gulp-manager, v0.2.17
gulp-snippets, v0.6.2
haskell-ghc-mod, v1.2.0
ide-haskell-cabal, v1.0.0
jsformat, v0.9.0
language-d, v3.2.1
language-haskell, v1.5.1
language-rust, v0.4.5
linter, v1.11.3
linter-gcc, v0.5.8
linter-rust, v0.3.0
linter-stylint, v2.0.1
minimap, v4.18.0
php-debug, v0.1.4
pigments, v0.19.3
pretty-json, v0.4.1
project-manager, v2.6.5
python-tools, v0.6.7
quick-docs, v0.1.0
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
atomize-d, v0.1.0
```

**Comment by maxbrunsfeld** [comment]
@kniteli Can you remove the `~/.atom/blob-store` and `~/.atom/compile-cache` and see if this still happens? If this workaround stops this exception from happening, I believe this issue will be fixed in the next release.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
