### ISSUE TITLE
Failed to load the vim-mode package

### ISSUE THREAD

**Issue by Vinnl** [atom/vim-mode#942]
(Note: Atom redirected me to #892 when it failed to load the `vim-mode` package for me. However, I'm not running Windows, and there are no special characters in my name, so I'm thinking this s a new issue.)

I recently upgraded the vim-mode package (not sure what the old version was, but probably the previous one). Ever since, I've been getting the below error message, and vim-mode isn't active. Upgrading Atom from 1.2.1 to 1.3.2 didn't help.

**Atom Version**: 1.3.2
**System**: Ubuntu 15.10
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.64.0

### Stack Trace

Failed to load the vim-mode package

```
At Cannot find module 'mixto'

Error: Cannot find module 'mixto'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:6:11)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/node_modules/property-accessors/lib/property-accessors.js:74:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/lib/behavior.js:9:23)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/lib/behavior.js:120:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/lib/helpers.js:5:14)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/lib/helpers.js:55:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/lib/emissary.js:4:13)
    at Object.<anonymous> (/home/rs55df/.atom/packages/vim-mode/node_modules/grim/node_modules/emissary/lib/emissary.js:14:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "vim-mode": {
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
emmet, v2.3.17
language-javascript-jsx, v0.3.7
linter, v1.11.3
minimap, v4.18.4
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by Habu-Kagumba** [comment]
Getting errors also after updating

**Atom Version**: 1.2.4
**System**: elementary OS
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.64.0


### Stack Trace

Failed to load the vim-mode package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/herbert/.atom/packages/vim-mode/lib/vim-state.coffee:1:9)
    at Object.<anonymous> (/home/herbert/.atom/packages/vim-mode/lib/vim-state.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/herbert/Projects",
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "vim-mode": {}
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.4.1
linter, v1.11.3
linter-flake8, v1.9.3
linter-js-standard, v3.2.1
vim-mode, v0.64.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
@Habu-Kagumba you should probably update to the latest version of Atom (v1.3.2) and see if it occurs again.

**Comment by kniteli** [comment]
I'm getting the same issue on v1.3.3

**Comment by polybuildr** [comment]
+1, issue occurring for me too. Running on Ubuntu 14.04. Atom version is 1.5.3

**Comment by polybuildr** [comment]
For me, the module was `event-kit`.

**Comment by polybuildr** [comment]
Sorry! This was an issue on my end. I installed the package using `git` and so I didn't have any of the packages it required. An `npm install` seems to have fixed it. :)

**Comment by 50Wliu** [comment]
@polybuildr: For next time, please use `apm install` instead.  `npm` and `apm` have very subtle differences in how they install modules that could lead to conflicts with Atom.

**Comment by polybuildr** [comment]
@50Wliu, thanks for the advice - will keep that in mind. I generally refrain from using `apm` due to some annoying proxy server issues that I seem to have fixed with `npm` but haven't managed to resolve for `apm`.

**Comment by Vinnl** [comment]
I just upgrade to vim-mode 0.65, and the issue no longer seems to appear. @Habu-Kagumba I'm closing this, could you check whether it still happens for you with a recent version of Atom and vim-mode, and if so, re-open it? (Or let me know, if you can't re-open it.)
