### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

### ISSUE THREAD

**Issue by tttlkkkl** [atom/vim-mode#952]
C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-keymap\lib\helpers.js:345
Hide Stack Trace
TypeError: Cannot read property 'keyIdentifier' of undefined
  at keyForKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-keymap\lib\helpers.js:345:26)
  at exports.keystrokeForKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-keymap\lib\helpers.js:162:11)
  at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:385:14)
  at VimState.module.exports.VimState.repeatPrefix (C:\Users\Administrator\.atom\packages\vim-mode\lib\vim-state.coffee:590:33)
  at atom-text-editor.registerCommands.repeat-prefix (C:\Users\Administrator\.atom\packages\vim-mode\lib\vim-state.coffee:71:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\src\command-registry.js:240:29)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Administrator\AppData\Local\atom\app-1.0.13\resources\app.asar\src\window-event-handler.js:184:20)

**Comment by tttlkkkl** [comment]
This error occurred when I pressed the number and capital G button.

**Comment by 50Wliu** [comment]
Hi @tttlkkkl, you're on a very outdated version of Atom that was released almost half a year ago.  I would suggest updating to the latest version, Atom 1.4.0, and also updating `vim-mode` and seeing if the error occurs again.  If it does, please comment here and I'll gladly re-open this issue.  Thanks!

**Comment by tttlkkkl** [comment]
Okay,thanks!
