### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by docmoxie** [atom/vim-mode#959]
[Enter steps to reproduce below:]
1. open vim search (/ key)
2. close tab
3. type search term and hit enter.

Should either: search on current tab, or pop you out of vim search mode upon tab closure.

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.64.0
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Users/marnold/.atom/packages/vim-mode/lib/vim-state.coffee:276

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:685:20)
    at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:690:51)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:675:21)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:80:19)
    at SearchBase.moveCursor (/Users/marnold/.atom/packages/vim-mode/lib/motions/search-motion.coffee:23:14)
    at Search.Motion.execute (/Users/marnold/.atom/packages/vim-mode/lib/motions/general-motions.coffee:37:8)
    at VimState.module.exports.VimState.processOpStack (/Users/marnold/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.processOpStack (/Users/marnold/.atom/packages/vim-mode/lib/vim-state.coffee:271:10)
    at VimState.module.exports.VimState.pushOperations (/Users/marnold/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at SearchViewModel.ViewModel.confirm (/Users/marnold/.atom/packages/vim-mode/lib/view-models/view-model.coffee:11:15)
    at SearchViewModel.module.exports.SearchViewModel.confirm (/Users/marnold/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:41:5)
    at SearchViewModel.confirm (/Users/marnold/.atom/packages/vim-mode/lib/view-models/search-view-model.coffee:1:1)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (/Users/marnold/.atom/packages/vim-mode/lib/view-models/vim-normal-mode-input-element.coffee:45:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:34.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:34.4.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:31 vim-mode:search (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:31 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:29.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 vim-mode:change (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:27 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
  2x -0:09.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.1.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:07.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:06.2.0 vim-mode:search (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:06.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:04.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "vim-mode": {}
}
```
### Installed Packages

``` coffee
# User
language-haskell, v1.5.2
minimap, v4.19.0
pigments, v0.21.0
terminal-plus, v0.14.5
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by yukitoto** [comment]
I have same issue

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
