### ISSUE TITLE
Uncaught TypeError: patch.getChanges is not a function

### ISSUE THREAD

**Issue by li-xinyang** [atom/vim-mode#989]
[Enter steps to reproduce below:]
1. Shift-o
2. ...

**Atom Version**: 1.7.0-beta0
**System**: Ubuntu 14.04.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.65.0
### Stack Trace

Uncaught TypeError: patch.getChanges is not a function

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1333

TypeError: patch.getChanges is not a function
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1333:60)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:843:12)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1274:26)
    at TextEditor.module.exports.TextEditor.insertNewlineAbove (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1175:19)
    at InsertAboveWithNewline.execute (/home/li-xinyang/.atom/packages/vim-mode/lib/operators/input.coffee:71:13)
    at VimState.module.exports.VimState.processOpStack (/home/li-xinyang/.atom/packages/vim-mode/lib/vim-state.coffee:279:23)
    at VimState.module.exports.VimState.pushOperations (/home/li-xinyang/.atom/packages/vim-mode/lib/vim-state.coffee:237:8)
    at atom-text-editor.commands.(anonymous function) (/home/li-xinyang/.atom/packages/vim-mode/lib/vim-state.coffee:209:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:17.6.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:15.5.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.4.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.4.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.1.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.1.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:07.8.0 editor:delete-to-beginning-of-subword (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:03.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:03.5.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  4x -0:03.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.6.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:02.3.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:01.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.2.0 vim-mode:insert-above-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.1.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "welcome",
      "vim-surround",
      "hyperclick",
      "js-hyperclick",
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.27
atom-ternjs, v0.13.2
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
docblockr, v0.7.3
linter, v1.11.4
linter-jshint, v2.0.3
linter-pep8, v1.2.1
pigments, v0.25.0
project-manager, v2.7.6
terminal-plus, v0.14.5
vim-mode, v0.65.0
wordcount, vundefined

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
